* Suggested SMF42 header fields — VERIFY IFASMFR labels on z/OS
* Generated from IBM Docs scrape (catalog/smf42)
TABLE42   SMF_START

         SMF_FIELD SMF42RTY-SMF42RCL,TYPE=T_DEC1,JSON=rty

         SMF_FIELD SMF42SID-SMF42RCL,TYPE=T_CHR4,JSON=sid

         SMF_FIELD SMF42SSI-SMF42RCL,TYPE=T_CHR4,JSON=ssi

         SMF_FIELD SMF42STY-SMF42RCL,TYPE=T_DEC2,JSON=sty

         SMF_FIELD SMF42TME-SMF42RCL,TYPE=T_TME,JSON=tme

         SMF_FIELD SMF42DTE-SMF42RCL,TYPE=T_DTE,JSON=dte

         SMF_END
