"""Auto-generated layouts for SMF 119 subtype 5 (from PACSYS offset tables)."""
from __future__ import annotations

from ..layout import (
    BYTES,
    CHAR,
    IPV4,
    IPV6MAPPED,
    RES,
    U8,
    U16,
    U32,
    U64,
    VAR_EBCDIC,
    build_layout,
)
from ..registry import SectionSlot

AP_TSIP_S1 = build_layout(
    "SMF119AP_TSIP_S1",
    [
        U64("SMF119AP_TSIPDuration", "Duration of recording interval in microseconds, where bit 51 is equivalent to one microsecond"),
        U32("SMF119AP_TSIPRecData", "Number of datagrams received"),
        RES("_pad_12", 8),
        U32("SMF119AP_TSIPAttFwdData", "Number of attempts to forward datagrams"),
        RES("_pad_24", 8),
        U32("SMF119AP_TSIPDlvData", "Number of datagrams delivered"),
        U32("SMF119AP_TSIPXData", "Number of datagrams transmitted"),
        U32("SMF119AP_TSIPXDscOth", "Number of outbound transmitted datagrams discarded, due to reasons other than no route being available"),
        U32("SMF119AP_TSIPXDscRoute", "Number of outbound transmitted datagrams discarded, due to no route being available"),
        U32("SMF119AP_TSIPTimeouts", "Number of reassembly timeouts"),
        U32("SMF119AP_TSIPRecDRsbm", "Number of received datagrams requiring assembly"),
        U32("SMF119AP_TSIPRsmb", "Number of datagrams reassembled"),
        U32("SMF119AP_TSIPFailRsmb", "Number of failed reassembly attempts"),
        U32("SMF119AP_TSIPRecFgmt", "Number of fragmented datagrams received"),
        U32("SMF119AP_TSIPDscDFgmt", "Number of discarded datagrams due to fragmentation failures"),
        U32("SMF119AP_TSIPXFgmt", "Number of fragments generated"),
        U32("SMF119AP_TSIPRouteDisc", "Number of routing discards"),
        U32("SMF119AP_TSIPMaxRsmb", "Maximum active number of reassemblies"),
        U32("SMF119AP_TSIPCurRsmb", "Number of currently active reassemblies"),
        U32("SMF119AP_TSIPRsmbFlags", "Reassembly flags"),
        U32("SMF119AP_TSIPInCalls", "Number of inbound calls from device layer"),
        U32("SMF119AP_TSIPInUerrs", "Number of received frame unpacking"),
        U32("SMF119AP_TSIPIDMem", "Number of discarded datagrams, due to memory shortages"),
        U32("SMF119AP_TSIPODSync", "Number of transmitted datagrams discarded, due to Sync errors"),
        U32("SMF119AP_TSIPODAsyn", "Number of transmitted datagrams discarded, due to Async errors"),
        U32("SMF119AP_TSIPODMem", "Number of transmitted datagrams discarded due to memory shortages"),
    ],
    description="SMF119AP_TSIP_S1",
)

AP_TSTC_S2 = build_layout(
    "SMF119AP_TSTC_S2",
    [
        U64("SMF119AP_TSTCDuration", "Duration of recording interval in microseconds, where bit 51 is equivalent to one microsecond"),
        U32("SMF119AP_TSTCAlg", "Retransmission algorithm"),
        U32("SMF119AP_TSTCMinRet", "Minimum retransmission time, in milliseconds"),
        U32("SMF119AP_TSTCMxRet", "Maximum retransmission time, in milliseconds"),
        U32("SMF119AP_TSTCMxCon", "Maximum TCP connections"),
        U32("SMF119AP_TSTCOpenConn", "Number of active open connections"),
        U32("SMF119AP_TSTCPassConn", "Number of passive open connections"),
        U32("SMF119AP_TSTCOFails", "Number of open connection failures"),
        U32("SMF119AP_TSTCConReset", "Number of connection resets"),
        U32("SMF119AP_TSTCEstab", "Number of current establishments"),
        U32("SMF119AP_TSTCInSegs", "Number of input TCP segments"),
        U32("SMF119AP_TSTCOSegs", "Number of output TCP segments"),
        U32("SMF119AP_TSTCRxSegs", "Number of retransmitted segments"),
        U32("SMF119AP_TSTCInErrs", "Number of input errors"),
        U32("SMF119AP_TSTCReset", "Number of resets"),
        U32("SMF119AP_TSTCConCls", "Number of TCP connections closed"),
        U32("SMF119AP_TSTCConAttD", "Number of TCP connection attempts discarded"),
        U32("SMF119AP_TSTCTWRef", "Number of TCP Timewait connections refused"),
        U32("SMF119AP_TSTCHOKAck", "Number of header predictions (OK for ACK)"),
        U32("SMF119AP_TSTCHOKDat", "Number of header predictions (OK for Data)"),
        U32("SMF119AP_TSTCIDupAck", "Number of duplicate ACKs received"),
        U32("SMF119AP_TSTCDscChecksum", "Number of received packets discarded due to bad checksum values"),
        U32("SMF119AP_TSTCDscLen", "Number of received packets discarded due to bad header length"),
        U32("SMF119AP_TSTCDscInsData", "Number of received packets discarded due to insufficient data"),
        U32("SMF119AP_TSTCDscOldTime", "Number of received packets discarded due to old timestamp information"),
        U32("SMF119AP_TSTCICmpDupSeg", "Number of received complete duplicate segments"),
        U32("SMF119AP_TSTCIPartDupSeg", "Number of received partial duplicate segments"),
        U32("SMF119AP_TSTCICmpSegsWin", "Number of complete segments received after window closure"),
        U32("SMF119AP_TSTCIPartSegsWin", "Number of partial segments received after window closure"),
        U32("SMF119AP_TSTCIOOrder", "Number of out of order segments received"),
        U32("SMF119AP_TSTCISegCls", "Number of segments received after the TCP connection closed"),
        U32("SMF119AP_TSTCIWinPr", "Number of received window probes"),
        U32("SMF119AP_TSTCIWinUp", "Number of received window updates"),
        U32("SMF119AP_TSTCOWinPr", "Number of transmitted window probes"),
        U32("SMF119AP_TSTCOWinUp", "Number of transmitted window updates"),
        U32("SMF119AP_TSTCODlAck", "Number of transmitted delayed ACKs"),
        U32("SMF119AP_TSTCOKApr", "Number of transmitted keepalive probes"),
        U32("SMF119AP_TSTCRxTim", "Number of retransmitted timeouts"),
        U32("SMF119AP_TSTCRxMTU", "Number of retransmitted Path MTU discovery packets"),
        U32("SMF119AP_TSTCPathM", "Number of Path MTUs beyond retransmit limit"),
        U32("SMF119AP_TSTCDropPr", "Number of TCP connections dropped due to probes"),
        U32("SMF119AP_TSTCDropKA", "Number of TCP connections dropped while in KeepAlive state"),
        U32("SMF119AP_TSTCDropF2", "Number of TCP connections dropped while in FINWAIT2 state"),
        U32("SMF119AP_TSTCDropRx", "Number of TCP connections dropped due to retransmits"),
    ],
    description="SMF119AP_TSTC_S2",
)

AP_TSUD_S3 = build_layout(
    "SMF119AP_TSUD_S3",
    [
        U64("SMF119AP_TSUDDuration", "Duration of recording interval in microseconds, where bit 51 is equivalent to one microsecond"),
        U64("SMF119AP_TSUDRecData", "Number of UDP datagrams received"),
        U32("SMF119AP_TSUDRecNoPort", "Number of UDP datagrams received with no port defined"),
        U32("SMF119AP_TSUDNoRec", "Number of other UDP datagrams not received"),
        U64("SMF119AP_TSUDXmtData", "Number of UDP datagrams sent"),
    ],
    description="SMF119AP_TSUD_S3",
)

AP_TSIC_S4 = build_layout(
    "SMF119AP_TSIC_S4",
    [
        U64("SMF119AP_TSICDuration", "Duration of recording interval in microseconds, where bit 51 is equivalent to one microsecond"),
        U32("SMF119AP_TSICInMsg", "Number of inbound ICMP messages"),
        U32("SMF119AP_TSICInError", "Number of inbound ICMP error messages"),
        U32("SMF119AP_TSICInDstUnreach", "Number of inbound ICMP destination unreachable messages"),
        U32("SMF119AP_TSICInTimeExcd", "Number of inbound ICMP time exceeded messages"),
        U32("SMF119AP_TSICInParmProb", "Number of inbound ICMP parameter problem messages"),
        U32("SMF119AP_TSICInSrcQuench", "Number of inbound ICMP source quench messages"),
        U32("SMF119AP_TSICInRedirect", "Number of inbound ICMP redirect messages"),
        U32("SMF119AP_TSICInEcho", "Number of inbound ICMP echo request messages"),
        U32("SMF119AP_TSICInEchoRep", "Number of inbound ICMP echo reply messages"),
        U32("SMF119AP_TSICInTstamp", "Number of inbound ICMP timestamp request messages"),
        U32("SMF119AP_TSICInTstampRep", "Number of inbound ICMP timestamp reply messages"),
        U32("SMF119AP_TSICInAddrMask", "Number of inbound ICMP address mask request messages"),
        U32("SMF119AP_TSICInAddrMRep", "Number of inbound ICMP address mask reply messages"),
        U32("SMF119AP_TSICOutMsg", "Number of outbound ICMP messages"),
        U32("SMF119AP_TSICOutError", "Number of outbound ICMP error messages"),
        U32("SMF119AP_TSICOutDstUnreach", "Number of outbound ICMP destination unreachable messages"),
        U32("SMF119AP_TSICOutTimeExcd", "Number of outbound ICMP time exceeded messages"),
        U32("SMF119AP_TSICOutParmProb", "Number of outbound ICMP parameter problem messages"),
        U32("SMF119AP_TSICOutSrcQuench", "Number of outbound ICMP source quench messages"),
        U32("SMF119AP_TSICOutRedirect", "Number of outbound ICMP redirect messages"),
        U32("SMF119AP_TSICOutEcho", "Number of outbound ICMP echo request messages"),
        U32("SMF119AP_TSICOutEchoRep", "Number of outbound ICMP echo reply messages"),
        U32("SMF119AP_TSICOutTstamp", "Number of outbound ICMP timestamp request messages"),
        U32("SMF119AP_TSICOutTstampRep", "Number of outbound ICMP timestamp reply messages"),
        U32("SMF119AP_TSICOutAddrMask", "Number of outbound ICMP address mask request messages"),
        U32("SMF119AP_TSICOutAddrMRep", "Number of outbound ICMP address mask reply messages"),
    ],
    description="SMF119AP_TSIC_S4",
)

AP_TSP6_S5 = build_layout(
    "SMF119AP_TSP6_S5",
    [
        U64("SMF119AP_TSP6Duration", "Duration of recording interval in microseconds, where bit 51 is equivalent to one microsecond"),
        U32("SMF119AP_TSP6RecData", "Number of IPv6 datagrams received"),
        RES("_pad_12", 8),
        U32("SMF119AP_TSP6AttFwdData", "Number of attempts to forward IPv6 datagrams"),
        RES("_pad_24", 8),
        U32("SMF119AP_TSP6DlvData", "Number of IPv6 datagrams delivered"),
        U32("SMF119AP_TSP6XData", "Number of IPv6 datagrams transmitted"),
        U32("SMF119AP_TSP6XDscOth", "Number of IPv6 outbound datagrams discarded, due to reasons other than no route being available"),
        U32("SMF119AP_TSP6XDscRoute", "Number of IPv6 outbound datagrams discarded, due to no route being available"),
        U32("SMF119AP_TSP6Timeouts", "Number of IPv6 reassembly timeouts"),
        U32("SMF119AP_TSP6RecDRsmb", "Number of received IPv6 datagrams requiring reassembly"),
        U32("SMF119AP_TSP6Rsmb", "Number of received IPv6 datagrams reassembled"),
        U32("SMF119AP_TSP6FailRsmb", "Number of failed reassembly attempts on IPv6 datagrams"),
        U32("SMF119AP_TSP6RecFgmt", "Number of fragmented IPv6 datagrams received"),
        U32("SMF119AP_TSP6DscDFgmt", "Number of IPv6 datagrams discarded due to fragmentation failure"),
        U32("SMF119AP_TSP6XFgmt", "Number of IPv6 datagram fragments generated"),
        U32("SMF119AP_TSP6RouteDisc", "Number of IPv6 routing discards"),
    ],
    description="SMF119AP_TSP6_S5",
)

AP_TSC6_S6 = build_layout(
    "SMF119AP_TSC6_S6",
    [
        U64("SMF119AP_TSC6Duration", "Duration of recording interval in microseconds, where bit 51 is equivalent to one microsecond"),
        U32("SMF119AP_TSC6InMsg", "Number of inbound IPv6 ICMP messages"),
        U32("SMF119AP_TSC6InError", "Number of inbound IPv6 ICMP error messages"),
        U32("SMF119AP_TSC6InDstUnreach", "Number of inbound IPv6 ICMP destination unreachable messages"),
        U32("SMF119AP_TSC6InTimeExcd", "Number of inbound IPv6 ICMP time exceeded messages"),
        U32("SMF119AP_TSC6InParmProb", "Number of inbound IPv6 ICMP parameter problem messages"),
        U32("SMF119AP_TSC6InAdmProhib", "Number of inbound IPv6 ICMP administratively prohibited messages"),
        U32("SMF119AP_TSC6InPktTooBig", "Number of inbound IPv6 ICMP packet too big messages"),
        U32("SMF119AP_TSC6InEcho", "Number of inbound IPv6 ICMP echo request messages"),
        U32("SMF119AP_TSC6InEchoRep", "Number of inbound IPv6 ICMP echo reply messages"),
        U32("SMF119AP_TSC6InRtSolicit", "Number of inbound IPv6 ICMP router solicitation messages"),
        U32("SMF119AP_TSC6InRtAdv", "Number of inbound IPv6 ICMP router advertisement messages"),
        U32("SMF119AP_TSC6InNbSolicit", "Number of inbound IPv6 ICMP neighbor solicitation messages"),
        U32("SMF119AP_TSC6InNbAdv", "Number of inbound IPv6 ICMP neighbor advertisement messages"),
        U32("SMF119AP_TSC6InRedirect", "Number of inbound IPv6 ICMP redirect messages"),
        U32("SMF119AP_TSC6InGrpMemQry", "Number of inbound IPv6 ICMP multicast listener discovery membership query messages"),
        U32("SMF119AP_TSC6InGrpMemRsp", "Number of inbound IPv6 ICMP multicast listener discovery membership reply messages"),
        U32("SMF119AP_TSC6InGrpMemRed", "Number of inbound IPv6 ICMP multicast listener discovery membership reduction messages"),
        U32("SMF119AP_TSC6OutMsg", "Number of outbound IPv6 ICMP messages"),
        U32("SMF119AP_TSC6OutError", "Number of outbound IPv6 ICMP error messages"),
        U32("SMF119AP_TSC6OutDstUnrch", "Number of outbound IPv6 ICMP destination unreachable messages"),
        U32("SMF119AP_TSC6OutTimeExcd", "Number of outbound IPv6 ICMP time exceeded messages"),
        U32("SMF119AP_TSC6OutParmProb", "Number of outbound IPv6 ICMP parameter problem messages"),
        U32("SMF119AP_TSC6OutAdmProhib", "Number of outbound IPv6 ICMP administratively prohibited messages"),
        U32("SMF119AP_TSC6OutPktTooBig", "Number of outbound IPv6 ICMP packet too big messages"),
        U32("SMF119AP_TSC6OutEcho", "Number of outbound IPv6 ICMP echo request messages"),
        U32("SMF119AP_TSC6OutEchoRep", "Number of outbound IPv6 ICMP echo reply messages"),
        U32("SMF119AP_TSC6OutRtSolicit", "Number of outbound IPv6 ICMP router solicitation messages"),
        U32("SMF119AP_TSC6OutRtAdv", "Number of outbound IPv6 ICMP router advertisement messages"),
        U32("SMF119AP_TSC6OutNbSolicit", "Number of outbound IPv6 ICMP neighbor solicitation messages"),
        U32("SMF119AP_TSC6OutNbAdv", "Number of outbound IPv6 ICMP neighbor advertisement messages"),
        U32("SMF119AP_TSC6OutRedirect", "Number of outbound IPv6 ICMP redirect messages"),
        U32("SMF119AP_TSC6OutGrpMemQry", "Number of outbound IPv6 ICMP multicast listener discovery membership query messages"),
        U32("SMF119AP_TSC6OutGrpMemRsp", "Number of outbound IPv6 ICMP multicast listener discovery membership report messages"),
        U32("SMF119AP_TSC6OutGrpMemRed", "Number of outbound IPv6 ICMP multicast listener discovery membership reduction messages"),
    ],
    description="SMF119AP_TSC6_S6",
)

SECTION_SLOTS = [
    SectionSlot(triplet_index=1, key='S1', layout=AP_TSIP_S1),
    SectionSlot(triplet_index=2, key='S2', layout=AP_TSTC_S2),
    SectionSlot(triplet_index=3, key='S3', layout=AP_TSUD_S3),
    SectionSlot(triplet_index=4, key='S4', layout=AP_TSIC_S4),
    SectionSlot(triplet_index=5, key='S5', layout=AP_TSP6_S5),
    SectionSlot(triplet_index=6, key='S6', layout=AP_TSC6_S6),
]

__all__ = ['AP_TSIP_S1', 'AP_TSTC_S2', 'AP_TSUD_S3', 'AP_TSIC_S4', 'AP_TSP6_S5', 'AP_TSC6_S6', "SECTION_SLOTS"]
