"""Auto-generated layouts for SMF 119 subtype 11 (from PACSYS offset tables)."""
from __future__ import annotations

from ..layout import (
    BYTES,
    CHAR,
    IPV4,
    IPV6MAPPED,
    RES,
    U8,
    U16,
    U32,
    U64,
    VAR_EBCDIC,
    build_layout,
)
from ..registry import SectionSlot

SC_SA_S1 = build_layout(
    "SMF119SC_SA_S1",
    [
        U8("SMF119SC_SAEvent_Type", "Event type: X'01': Connection initiation X'02': Change in cryptographic attributes X'03': Connection termination X'04': Short connection termination (Connection terminates within 10 seconds of being established. No associated Connection ini"),
        U8("SMF119SC_SASecProtos", "Cryptographic security protocols for the connection. Zero or more of these flags may be specified: X'00': No recognized cryptographic protection X'80': TLS/SSL X'40': SSH X'20': IPSec"),
        U8("SMF119SC_SAFlags", "Flags: X'80': IPv6 connection X'40': AT-TLS cryptographic data protection operations are bypassed for this connection as part of a stack optimization for intra-host connections. Only AT-TLS peer authentication operations are executed in thi"),
        U8("SMF119SC_SASecFlags", "IP security Flags: x'80': IP security is enabled x'40': IPv6 security is enabled x'20': IP filtering done for connection"),
        U8("SMF119SC_SAIPProto", "IP Protocol value: X'06': TCP X'11': UDP"),
        BYTES("SMF119SC_SA_Rsvd1", 3, "Reserved"),
        CHAR("SMF119SC_SAJobname", 8, "Jobname associated with the socket"),
        CHAR("SMF119SC_SAJobID", 8, "Job ID associated with the socket"),
        CHAR("SMF119SC_SAUserID", 8, "z/OS® user ID associated with the socket"),
        U32("SMF119SC_SASTime", "Time of day of connection establishment in 1/100 seconds since midnight (using Coordinated Universal Time (UTC))"),
        BYTES("SMF119SC_SASDate", 4, "Date of connection establishment (UTC)", decode="date_hex"),
        U32("SMF119SC_SAETime", "Time connection ended in 1/100 seconds since midnight (using Coordinated Universal Time (UTC))"),
        BYTES("SMF119SC_SAEDate", 4, "Date connection end, set when event type (SMF119SC_SAEvent_Type) is connection termination or short connection termination otherwise, 0", decode="date_hex"),
        IPV6MAPPED("SMF119SC_SARIP", "Remote connection endpoint IP address. If SMF119SC_SAFlags indicates IPv6, then this is a 16-byte IPv6 address. Otherwise, it is a 4-byte IPv4 address in the first 4 bytes of the field."),
        IPV6MAPPED("SMF119SC_SALIP", "Local connection endpoint IP address. If SMF119SC_SAFlags indicates IPv6, then this is a 16-byte IPv6 address. Otherwise, it is a 4-byte IPv4 address in the first 4 bytes of the field."),
        U16("SMF119SC_SARPort", "Remote port"),
        U16("SMF119SC_SALPort", "Local port"),
        U32("SMF119SC_SAConnID", "Transport layer connection ID"),
        U64("SMF119SC_SAInBytes", "Inbound byte count since connection started"),
        U64("SMF119SC_SAOutBytes", "Outbound byte count since connection started"),
        U64("SMF119SC_SAInSegDG", "Inbound TCP segment or UDP datagram count since connection started"),
        U64("SMF119SC_SAOutSegDG", "Outbound TCP segment or UDP datagram count since connection started"),
        U64("SMF119SC_SA_Rsvd2", "Reserved"),
    ],
    description="SMF119SC_SA_S1",
)

SC_IPFlt_S2 = build_layout(
    "SMF119SC_IPFlt_S2",
    [
        U8("SMF119SC_IPFlt_OutAct", "Outbound IP filtering behavior: X'01': Outbound traffic permitted in the clear X'02': Outbound traffic permitted with IPSec protection X'03': Outbound traffic denied X'00' if no associated outbound filter rule). A change in this attribute c"),
        U8("SMF119SC_IPFlt_InbAct", "Inbound IP filtering behavior: X'01': Inbound traffic permitted in the clear X'02': Inbound traffic permitted with IPSec protection X'03': Inbound traffic denied X'00' if no associated inbound filter rule). A change in this attribute causes"),
        U16("SMF119SC_IPFlt_Rsvd1", "Reserved"),
        CHAR("SMF119SC_IPFlt_OutRuleName", 40, "Outbound traffic IP filter rule name (blank if no associated outbound filter rule)"),
        CHAR("SMF119SC_IPFlt_OutRuleExt", 8, "Outbound traffic IP filter rule name extension (blank if no associated outbound filter rule or the filter rule has no rule name extension value)"),
        CHAR("SMF119SC_IPFlt_InRuleName", 40, "Inbound traffic IP filter rule name (blank if no associated inbound filter rule)"),
        CHAR("SMF119SC_IPFlt_InRuleExt", 8, "Inbound traffic IP filter rule name extension (blank if no associated inbound filter rule or the filter rule has no rule name extension value)"),
    ],
    description="SMF119SC_IPFlt_S2",
)

SC_TLS_S3 = build_layout(
    "SMF119SC_TLS_S3",
    [
        U16("SMF119SC_TLS_Prot_Ver", "Protocol version: X'0000': Unknown version X'0200': SSLv2 X'0300': SSLv3 X'0301': TLSv1.0 X'0302': TLSv1.1 X'0303': TLSv1.2"),
        U8("SMF119SC_TLS_Source", "Source of the TLS/SSL information in this record: X'01': Stream observation X'02': Cryptographic protocol provider Information only"),
        U8("SMF119SC_TLS_Handshake_Type", "Handshake type: X'01': Full handshake X'02': Abbreviated handshake Information only"),
        U8("SMF119SC_TLS_Handshake_Role", "Local handshake role: X'00': Unknown X'01': Client X'02': Server X'03': Server with client authentication Information only"),
        U16("SMF119SC_TLS_Rsvd1", "Reserved"),
        U8("SMF119SC_TLS_Session_ID_Len", "Length of TLS session ID value in bytes. Information only"),
        BYTES("SMF119SC_TLS_Session_ID", 32, "TLS session ID (left justified). Information only"),
        CHAR("SMF119SC_TLS_Protocol_Provider", 16, "Source of the information in this record (padded with trailing blanks): \"Observation\": Information was observed by the TCP/IP stack, not supplied by a CPP. This value is used when SMF119SC_TLS_Source is set to 1. \"IBM System SSL\" : System S"),
        CHAR("SMF119SC_TLS_Neg_Cipher", 6, "Negotiated cipher suite identifier. If the TLS version is SSLv3 or higher, this is a four character value in the first 4 bytes of this field, padded with trailing blanks. Refer to the TLS Cipher Suite registry for a complete list of the 4-h"),
        U16("SMF119SC_TLS_CS_Enc_Alg", "The symmetric encryption algorithm used by the cipher suite: X'0000': Unknown X'0001': None X'0002': DES X'0003': DES 40 X'0004': 3DES X'0005': RC2 40 X'0006': RC2 128 X'0007': RC2 X'0008': RC4 40 X'0009': RC4 128 X'000A': RC4 256 X'000B': "),
        U16("SMF119SC_TLS_CS_Msg_Auth", "The message authentication algorithm used by the cipher suite: X'0000': Unknown X'0001': No message authentication, or uses authenticated encryption algorithm like AES-GCM X'0002': MD2 X'0003': HMAC-MD5 X'0004': HMAC-SHA1 X'0005': HMAC-SHA2"),
        U16("SMF119SC_TLS_CS_Kex_Alg", "The key exchange algorithm used by the cipher suite: X'0000': Unknown X'0001': None X'0002': RSA X'0003': RSA_EXPORT X'0004': RSA_PSK X'0005': DH_RSA X'0006': DH_RSA_EXPORT X'0007': DH_DSS X'0008': DH_ANON X'0009': DH_ANON_EXPORT X'000A': D"),
        U8("SMF119SC_TLS_FIPS_Mode", "FIPS 140 mode of the TLS/SSL provider: X'00': Not in FIPS 140 mode X'01': FIPS 140 mode is enabled (80-bit strength enforced) X'02': FIPS 140 mode is enabled at level 1 (synonymous with X'01') X'03': FIPS 140 mode is enabled at level 2 (112"),
        U8("SMF119SC_TLS_CryptoFlags", "Cryptographic operations flags: X'80': Encrypt-then-MAC processing is used All other flags reserved"),
        U16("SMF119SC_TLS_Rsvd2", "Reserved Server certificate information"),
        U16("SMF119SC_TLS_SCert_Signature_Method", "Server certificate signature method: X'0000': Unknown X'0001': None X'0002': RSA with MD2 X'0003': RSA with MD5 X'0004': RSA with SHA1 X'0005': DSA with SHA1 X'0006': RSA with SHA-224 X'0007': RSA with SHA-256 X'0008': RSA with SHA-384 X'00"),
        U16("SMF119SC_TLS_SCert_Enc_Method", "Server certificate encryption method: X'0000': Unknown X'0001': None X'0002': RSA X'0003': DSA X'0004': ECDSA"),
        U16("SMF119SC_TLS_SCert_Digest_Alg", "Server certificate digest algorithm: X'0000': Unknown X'0001': None X'0002': MD2 X'0003': MD5 X'0004': SHA1 X'0005': SHA-224 X'0006': SHA-256 X'0007': SHA-384 X'0008': SHA-512"),
        U8("SMF119SC_TLS_Rsvd3", "Reserved"),
        U8("SMF119SC_TLS_SCert_Serial_Len", "Server certificate serial number length in bytes. Information only"),
        BYTES("SMF119SC_TLS_SCert_Serial", 20, "Server certificate serial number, left justified. Information only"),
        U8("SMF119SC_TLS_SCert_Time_Type", "Format of server certificate \"not after\" time: X'01': Coordinated Universal Time (UTC) X'02': Generalized Time (GT) Information only"),
        BYTES("SMF119SC_TLS_SCert_Time", 15, "Server certificate \"not after\" time: If the time type is UTC (SMF119SC_TLS_SCert_Time_Type = X'01'), the first 13 bytes of this field contain the time in UTC format (YYMMDDhhmmssZ). If the time type is GT (SMF119SC_TLS_SCert_Time_Type = X'0"),
        U16("SMF119SC_TLS_SCert_Key_Type", "Server certificate key type: X'0000': Unknown X'0001': None X'0002': RSA X'0003': DSA X'0004': Diffie-Hellman (DH) X'0005': Elliptic Curve Cryptography (ECC)"),
        U16("SMF119SC_TLS_SCert_Key_Len", "Server certificate key length in bits Client certificate information"),
        U16("SMF119SC_TLS_CCert_Signature_Method", "Client certificate signature method. Same values as SMF119SC_TLS_SCert_Signature_Method."),
        U16("SMF119SC_TLS_CCert_Enc_Method", "Client certificate encryption method. Same values as SMF119SC_TLS_SCert_Enc_Method"),
        U16("SMF119SC_TLS_CCert_Digest_Alg", "Client certificate digest algorithm. Same values as SMF119SC_TLS_SCert_Digest_Alg"),
        U8("SMF119SC_TLS_Rsvd4", "Reserved"),
        U8("SMF119SC_TLS_CCert_Serial_Len", "Client certificate serial number length in bytes. Information only"),
        BYTES("SMF119SC_TLS_CCert_Serial", 20, "Client certificate serial number, left justified. Information only"),
        U8("SMF119SC_TLS_CCert_Time_Type", "Format of client certificate \"not after\" time: X'01': Coordinated Universal Time (UTC) X'02': Generalized Time (GT) Information only"),
        BYTES("SMF119SC_TLS_CCert_Time", 15, "Client certificate \"not after\" time: If the time type is UTC (SMF119SC_TLS_CCert_Time_Type = X'01'), the first 13 bytes of this field contain the time in UTC format (YYMMDDhhmmssZ). If the time type is GMT (SMF119SC_TLS_CCert_Time_Type = X'"),
        U16("SMF119SC_TLS_CCert_Key_Type", "Client certificate key type. Same values as SMF119SC_TLS_SCert_Key_Type."),
        U16("SMF119SC_TLS_CCert_Key_Len", "Client certificate key length in bits"),
    ],
    description="SMF119SC_TLS_S3",
)

SC_SSH_S4 = build_layout(
    "SMF119SC_SSH_S4",
    [
        U8("SMF119SC_SSH_Prot_Ver", "Protocol version: X'01': Protocol version 1 X'02': Protocol version 2"),
        U8("SMF119SC_SSH_Source", "Source of the SSH information in this record: X'01': Stream observation X'02': Cryptographic protocol provider Information only"),
        U8("SMF119SC_SSH_FIPS_Mode", "FIPS 140 mode of the SSH provider. Same values as SMF119SC_TLS_FIPS_Mode . Information only"),
        U8("SMF119SC_SSH_CryptoFlags", "Cryptographic operations flags: X'80': Encrypt-then-MAC processing is used for inbound traffic X'40' Encrypt-then-MAC processing is used for outbound traffic All other flags reserved"),
        U32("SMF119SC_SSH_Rsvd1", "Reserved"),
        CHAR("SMF119SC_SSH_Comp", 8, "SSH subcomponent (-padded with trailing blanks): 'SFTPS': sftp server 'SFTPC': sftp client 'SCPS ' : scp server 'SCPC' : scp client 'SSH' : ssh client 'SSHD' : sshd daemon Information only"),
        CHAR("SMF119SC_SSH_Protocol_Provider", 16, "Protocol provider (padded with trailing blanks): \"Observation\": Information was observed by the TCP/IP stack, not supplied by a CPP. This value is used when SMF119SC_SSH_Source is set to 1. \"IBM OpenSSH\": z/OS-provided OpenSSH Other values "),
        U16("SMF119SC_SSH_Auth_Method", "First or only peer authentication method used for this connection: X'0000': Unknown X'0001': None X'0002': Password X'0003': Public key X'0004': Host-based X'0005': Rhosts X'0006': RhostsRSA X'0007': RSA X'0008': Keyboard-interactive X'0009"),
        U16("SMF119SC_SSH_Auth_Method2", "If not 0, the last of multiple authentication methods used for this connection. Values are the same as those for SMF119SC_SSH_Auth_Method"),
        U16("SMF119SC_SSH_In_Enc_Alg", "Encryption algorithm for inbound traffic. Same values as SMF119SC_TLS_CS_Enc_Alg ."),
        U16("SMF119SC_SSH_In_Msg_Auth", "Message authentication algorithm for inbound traffic. Same values as SMF119SC_TLS_CS_Msg_Auth ."),
        U16("SMF119SC_SSH_Kex_Method", "Key exchange method. X'0000' Unknown X'0001' None X'0002' Diffie-Hellman-group-exchangeSHA256 X'0003' Diffie-Hellman-group-exchangeSHA1 X'0004' Diffie-Hellman-group14-SHA1 X'0005' Diffie-Hellman-group1-SHA1 X'0006' ECDH-SHA2-NISTP256 X'0007"),
        U16("SMF119SC_SSH_Out_Enc_Alg", "Encryption algorithm for outbound traffic. . Same values as SMF119SC_TLS_CS_Enc_Alg ."),
        U16("SMF119SC_SSH_Out_Msg_Auth", "Message authentication algorithm for outbound traffic. Same values as SMF119SC_TLS_CS_Msg_Auth ."),
        U16("SMF119SC_SSH_Rsvd2", "Reserved"),
        U16("SMF119SC_SSH_SKey_Type", "Type of raw server key: X'0000': Unknown X'0001': None X'0002': RSA X'0003': DSA X'0004': Diffie-Hellman (DH) X'0005': Elliptic Curve Cryptography (ECC) X'0006': RSA1 (SSHV1 only) X'0007': RSA_CERT (from OpenSSH certificate) X'0008': DSA_CE"),
        U16("SMF119SC_SSH_SKey_Len", "Length of raw server key in bits."),
        U16("SMF119SC_SSH_CKey_Type", "Type of raw client key. Same values as SMF119SC_SSH_SKey_Type."),
        U16("SMF119SC_SSH_CKey_Len", "Length of raw client key in bits."),
        U16("SMF119SC_SSH_SKey_FPLen", "Length (in bytes) of the server public key fingerprint. If no server public key is used, then this length is set to zero. Information only"),
        U16("SMF119SC_SSH_CKey_FPLen", "Length (in bytes) of the client public key fingerprint. If no client public key is used, then this length is set to zero. Information only"),
        BYTES("SMF119SC_SSH_SKey_FP", 64, "The server public key fingerprint (a hash of the public key used to identify that key), left justified and padded on the right with X’00’. Information only"),
        BYTES("SMF119SC_SSH_CKey_FP", 64, "The client public key fingerprint (a hash of the public key used to identify that key), left justified and padded on the right with X’00’. Information only Server X.509 certificate information"),
        U16("SMF119SC_SSH_SCert_Signature_Method", "Server certificate signature method. Same values as SMF119SC_TLS_SCert_Signature_Method ."),
        U16("SMF119SC_SSH_SCert_Enc_Method", "Server certificate encryption method. Same values as SMF119SC_TLS_SCert_Enc_Method ."),
        U16("SMF119SC_SSH_SCert_Digest_Alg", "Server certificate digest algorithm. Same values as SMF119SC_TLS_SCert_Digest_Alg ."),
        U8("SMF119SC_SSH_Rsvd3", "Reserved"),
        U8("SMF119SC_SSH_SCert_Serial_Len", "Server certificate serial number length in bytes. Information only"),
        BYTES("SMF119SC_SSH_SCert_Serial", 20, "Server certificate serial number, left justified. Information only"),
        U8("SMF119SC_SSH_SCert_Time_Type", "Format of server certificate \"not after\" time: X'01': Coordinated Universal Time (UTC) X'02': Generalized Time (GT) Information only"),
        BYTES("SMF119SC_SSH_SCert_Time", 15, "Server certificate \"not after\" time: If the time type is UTC (SMF119SC_SSH_SCert_Time_Type = X'01'), the first 13 bytes of this field contain the time in UTC format (YYMMDDhhmmssZ). If the time type is GT (SMF119SC_SSH_SCert_Time_Type = X'0"),
        U16("SMF119SC_SSH_SCert_Key_Type", "Server certificate key type. Same values as SMF119SC_TLS_SCert_Key_Type ."),
        U16("SMF119SC_SSH_SCert_Key_Len", "Server certificate key length in bits Client X.509 certificate information"),
        U16("SMF119SC_SSH_CCert_Signature_Method", "Client certificate signature method. Same values as SMF119SC_TLS_SCert_Signature_Method ."),
        U16("SMF119SC_SSH_CCert_Enc_Method", "Client certificate encryption method. Same values as SMF119SC_TLS_SCert_Enc_Method ."),
        U16("SMF119SC_SSH_CCert_Digest_Alg", "Client certificate digest algorithm. Same values as SMF119SC_TLS_SCert_Digest_Alg ."),
        U8("SMF119SC_SSH_Rsvd4", "Reserved"),
        U8("SMF119SC_SSH_CCert_Serial_Len", "Client certificate serial number length in bytes. Information only"),
        BYTES("SMF119SC_SSH_CCert_Serial", 20, "Client certificate serial number, left justified. Information only"),
        U8("SMF119SC_SSH_CCert_Time_Type", "Format of client certificate \"not after\" time: X'01': Coordinated Universal Time (UTC) X'02': Generalized Time (GT) Information only"),
        BYTES("SMF119SC_SSH_CCert_Time", 15, "Client certificate \"not after\" time: If the time type is UTC (SMF119SC_SSH_CCert_Time_Type = X'01'), the first 13 bytes of this field contain the time in UTC format (YYMMDDhhmmssZ). If the time type is GT (SMF119SC_SSH_CCert_Time_Type = X'0"),
        U16("SMF119SC_SSH_CCert_Key_Type", "Client certificate key type. Same values as SMF119SC_TLS_SCert_Key_Type ."),
        U16("SMF119SC_SSH_CCert_Key_Len", "Client certificate key length in bits"),
    ],
    description="SMF119SC_SSH_S4",
)

SC_IPSec_S5 = build_layout(
    "SMF119SC_IPSec_S5",
    [
        U32("SMF119SC_IPSec_IKETunID", "IKE tunnel identifier. This value is displayed as Ktunid in ipsec command displays. Information only"),
        U8("SMF119SC_IPSec_IKEMajVer", "Major version of the IKE protocol in use. Only the low-order 4 bits are used."),
        U8("SMF119SC_IPSec_IKEMinVer", "Minor version of the IKE protocol in use. Only the low-order 4 bits are used."),
        U16("SMF119SC_IPsec_Rsvd1", "Reserved"),
        CHAR("SMF119SC_IPSec_IKETunKeyExchRule", 48, "Key exchange rule for this IKE tunnel (padded with trailing blanks). Information only"),
        IPV6MAPPED("SMF119SC_IPSec_IKETunLclEndpt", "Local IP address of tunnel endpoint. If SMF119SC_Flags in the zERT common identification section indicates IPv6, then this is a 16-byte IPv6 address. Otherwise, it is a 4-byte IPv4 address in the first 4 bytes of the field."),
        IPV6MAPPED("SMF119SC_IPSec_IKETunRmtEndpt", "Remote IP address of tunnel endpoint. If SMF119SC_Flags in the zERT common identification section indicates IPv6, then this is a 16-byte IPv6 address. Otherwise, it is a 4-byte IPv4 address in the first 4 bytes of the field."),
        U16("SMF119SC_IPSec_IKETunLclAuthMeth", "The authentication method for the local endpoint. One of the following values: X'00': Unknown or manual tunnel X'01': None X'02': RSA signature X'03': Preshared key X'04': ECDSA-256 signature X'05': ECDSA-384 signature X'06': ECDSA-521 sign"),
        U16("SMF119SC_IPSec_IKETunRmtAuthMeth", "The authentication method for the remote endpoint. Same values as SMF119SC_IPSec_IKETunLclAuthMeth."),
        U16("SMF119SC_IPSec_IKETunAuthAlg", "Tunnel authentication algorithm. Same values as SMF119SC_TLS_CS_Msg_Auth ."),
        U16("SMF119SC_IPSec_IKETunEncAlg", "Tunnel encryption algorithm. Same values as SMF119SC_TLS_CS_Enc_Alg ."),
        U16("SMF119SC_IPSec_IKETunDHGroup", "Diffie-Hellman group used to generate the keying material for this IKE tunnel. One of the following values: X'00': Unknown or manual tunnel X'01': Group1 X'02': Group 2 X'05': Group 5 X'0E': Group 14 X'13': Group 19 X'14': Group 20 X'15': G"),
        U16("SMF119SC_IPSec_IKETunPseudoRandFunc", "Pseudo-random function used for seeding keying material. One of the following values: X'00': Unknown or manual tunnel X'01': None X'02': HMAC-SHA2-256 X'03': HMAC-SHA2-384 X'04': HMAC-SHA2-512 X'05': AES-128-XCBC X'06': HMAC-MD5 X'07': HMAC"),
        U32("SMF119SC_IPSec_IKETunLifesize", "IKE tunnel lifesize. If not 0, this value indicates the lifesize limit for the tunnel, in Kbytes. Otherwise (value is 0), no lifesize enforced. Information only"),
        U32("SMF119SC_IPSec_IKETunLifetime", "IKE tunnel lifetime. This value indicates the total number of minutes the tunnel remains active. Information only"),
        U32("SMF119SC_IPSec_IKETunReauthIntvl", "Reauthentication interval. Indicates the number of minutes between reauthentication operations. Information only"),
        U16("SMF119SC_IPSec_LclCert_Sign_Meth", "Local IKE certificate signature method. Same values as SMF119SC_TLS_SCert_Signature_Method ."),
        U16("SMF119SC_IPSec_LclCert_Enc_Meth", "Local IKE certificate encryption method. Same values as SMF119SC_TLS_SCert_Enc_Method ."),
        U16("SMF119SC_IPSec_LclCert_Digest_Alg", "Local IKE certificate digest algorithm. Same values as SMF119SC_TLS_SCert_Digest_Alg ."),
        U8("SMF119SC_IPsec_Rsvd2", "Reserved."),
        U8("SMF119SC_IPSec_LclCert_Serial_Len", "Local IKE certificate serial number length in bytes. Information only"),
        BYTES("SMF119SC_IPSec_LclCert_Serial", 20, "Local IKE certificate serial number, left justified. Information only"),
        U8("SMF119SC_IPSec_LclCert_Time_Type", "Format of local IKE certificate \"not after\" time: X'00': Manual tunnel - unused X'01': Coordinated Universal Time (UTC) X'02': Generalized Time (GT) Information only"),
        BYTES("SMF119SC_IPSec_LclCert_Time", 15, "Local IKE certificate \"not after\" time: If the time type is UTC (SMF119SC_IPSec_LclCert_Time_Type = X'01'), the first 13 bytes of this field contain the time in UTC format (YYMMDDhhmmssZ). If the time type is GT (SMF119SC_IPSec_LclCert_Time"),
        U16("SMF119SC_IPSec_LclCert_Key_Type", "Local IKE certificate key type. Same values as SMF119SC_TLS_SCert_Key_Type ."),
        U16("SMF119SC_IPSec_LclCert_Key_Len", "Local IKE certificate key length in bits."),
        U16("SMF119SC_IPSec_RmtCert_Sign_Meth", "Remote IKE certificate signature method. Same values as SMF119SC_TLS_SCert_Signature_Method ."),
        U16("SMF119SC_IPSec_RmtCert_Enc_Meth", "Remote IKE certificate encryption method. Same values as SMF119SC_TLS_SCert_Enc_Method ."),
        U16("SMF119SC_IPSec_RmtCert_Digest_Alg", "Remote IKE certificate digest algorithm. Same values as SMF119SC_TLS_SCert_Digest_Alg ."),
        U8("SMF119SC_IPSec_Rsvd3", "Reserved"),
        U8("SMF119SC_IPSec_RmtCert_Serial_Len", "Remote IKE certificate serial number length in bytes. Information only"),
        BYTES("SMF119SC_IPSec_RmtCert_Serial", 20, "Remote IKE certificate serial number, left justified. Information only"),
        U8("SMF119SC_IPSec_RmtCert_Time_Type", "Format of remote IKE certificate \"not after\" time: X'00': Manual tunnel - unused X'01': Coordinated Universal Time (UTC) X'02': Generalized Time (GT) Information only"),
        BYTES("SMF119SC_IPSec_RmtCert_Time", 15, "Remote IKE certificate \"not after\" time: If the time type is UTC (SMF119SC_IPSec_RmtCert_Time_Type = X'01'), the first 13 bytes of this field contain the time in UTC format (YYMMDDhhmmssZ). If the time type is GT (SMF119SC_IPSec_RmtCert_Tim"),
        U16("SMF119SC_IPSec_RmtCert_Key_Type", "Remote IKE certificate key type. Same values as SMF119SC_TLS_SCert_Key_Type ."),
        U16("SMF119SC_IPSec_RmtCert_Key_Len", "Remote IKE certificate key length in bits. IPsec (Phase 2) tunnel information"),
        U32("SMF119SC_IPSec_TunID", "IPSec tunnel identifier. This value is displayed as Ytunid or Mtunid in ipsec command displays. Information only"),
        U8("SMF119SC_IPSec_TunFlags", "IP tunnel flags: X'80': IPv6 indicator. If set, security endpoint addresses and data endpoint addresses are IPv6; otherwise, they are IPv4. X'40': FIPS 140 mode indicator. If this field is set, cryptographic operations for this tunnel are p"),
        U8("SMF119SC_IPSec_TunType", "Tunnel type. One of the following values: X'01': Manual IPSec tunnel X'02': Dynamic IPSec tunnel X'03': Shadow tunnel"),
        U8("SMF119SC_IPSec_TunState", "One of the following tunnel states: X'01': Manual or dynamic tunnel is active. X'02': Manual tunnel is inactive."),
        U8("SMF119SC_IPSec_Rsvd4", "Reserved"),
        U8("SMF119SC_IPSec_EncapMode", "One of the following tunnel encapsulation modes: X'01': Tunnel Mode X'02': Transport Mode"),
        U8("SMF119SC_IPSec_AuthProto", "The protocol used for message authentication. One of the following: X'32' Encapsulating Security Payload (ESP) X'33': Authentication Header (AH)"),
        U16("SMF119SC_IPSec_AuthAlg", "One of the following tunnel authentication algorithms. Same values as SMF119SC_TLS_CS_Msg_Auth ."),
        U16("SMF119SC_IPSec_EncAlg", "One of the following tunnel encryption algorithms. Same values as SMF119SC_TLS_CS_Enc_Alg ."),
        U16("SMF119SC_IPSec_PFSGroup", "Diffie-Hellman group used for perfect forward secrecy. Same values as SMF119SC_IPSec_IKETunDHGroup."),
        U32("SMF119SC_IPSec_Lifesize", "SA lifesize in KBytes. Zero if SMF119SC_IPSec_TunType is set to 1. Information only"),
        U32("SMF119SC_IPSec_Lifetime", "SA lifetime in minutes. Zero if SMF119SC_IPSec_TunType is set to 1. Information only"),
        U32("SMF119SC_IPSec_VPNLifeExpire", "Tunnel VPN lifetime in minutes (length of time after which the tunnel family ceases to be refreshed). Zero indicates no VPN lifetime limit is enforced. Information only"),
    ],
    description="SMF119SC_IPSec_S5",
)

SC_DN_S6 = build_layout(
    "SMF119SC_DN_S6",
    [
        U16("SMF119SC_DN_Len", "Length of the DN structure (includes the length of SMF119SC_DN_Len, SMF119SC_DN_Type, and SMF119SC_DN)"),
        U16("SMF119SC_DN_Type", "Type of Distinguished Name: X'0001': IPSec Local Certificate Subject DN X'0002': IPSec Local Certificate Issuer DN X'0003': IPSec Remote Certificate Subject DN X'0004': IPSec Remote Certificate Issuer DN X'0005': TLS Server Certificate Subj"),
        CHAR("SMF119SC_DN", 1024, "The variable length DN value (up to 1024)"),
    ],
    description="SMF119SC_DN_S6",
)

SECTION_SLOTS = [
    SectionSlot(triplet_index=1, key='S1', layout=SC_SA_S1),
    SectionSlot(triplet_index=2, key='S2', layout=SC_IPFlt_S2, optional=True),
    SectionSlot(triplet_index=3, key='S3', layout=SC_TLS_S3, optional=True),
    SectionSlot(triplet_index=4, key='S4', layout=SC_SSH_S4, optional=True),
    SectionSlot(triplet_index=5, key='S5', layout=SC_IPSec_S5, optional=True),
    SectionSlot(triplet_index=6, key='S6', layout=SC_DN_S6, optional=True),
]

__all__ = ['SC_SA_S1', 'SC_IPFlt_S2', 'SC_TLS_S3', 'SC_SSH_S4', 'SC_IPSec_S5', 'SC_DN_S6', "SECTION_SLOTS"]
