apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse_smf
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: smf
      port: 8123
      host: clickhouse
      protocol: http
      username: smf
      tlsSkipVerify: false
    secureJsonData:
      password: blacha123
