* Shared SMF type-30 field list (copied into TABLE30 / TABLE30_n)
         SMF_FIELD SMF30RTY-SMF30LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF30SID-SMF30LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF30TME-SMF30LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF30DTE-SMF30LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF30WID-SMF30LEN,TYPE=T_CHR4,JSON=work_class_id

         SMF_FIELD SMF30STP-SMF30LEN,TYPE=T_DEC2,JSON=subtype

         SMF_FIELD SMF30RVN-SMF30PSS,TRIPLET=SMF30SOF-SMF30LEN,        X
               TYPE=T_CHR2,JSON=rec_version

         SMF_FIELD SMF30PNM-SMF30PSS,TRIPLET=SMF30SOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=addr_space_ind

         SMF_FIELD SMF30OSL-SMF30PSS,TRIPLET=SMF30SOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=os_level

         SMF_FIELD SMF30SYN-SMF30PSS,TRIPLET=SMF30SOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=sys_name

         SMF_FIELD SMF30SYP-SMF30PSS,TRIPLET=SMF30SOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF30JBN-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=job_name

         SMF_FIELD SMF30PGM-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=program_name

         SMF_FIELD SMF30STM-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=step_name

         SMF_FIELD SMF30JNM-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=jes_job_num

         SMF_FIELD SMF30USR-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR20,JSON=user_name

         SMF_FIELD SMF30STN-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_DEC2,JSON=step_number

         SMF_FIELD SMF30CLS-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR1,JSON=job_class

         SMF_FIELD SMF30CL8-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=job_class8

         SMF_FIELD SMF30JPT-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_DEC2,JSON=jes_priority

         SMF_FIELD SMF30RST-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_TME,JSON=reader_start_t

         SMF_FIELD SMF30RSD-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_DTE,JSON=reader_start_d

         SMF_FIELD SMF30SIT-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_TME,JSON=step_init_t

         SMF_FIELD SMF30STD-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_DTE,JSON=step_init_d

         SMF_FIELD SMF30GRP-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=racf_group

         SMF_FIELD SMF30RUD-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_CHR8,JSON=racf_user

         SMF_FIELD SMF30ASI-SMF30JBN,TRIPLET=SMF30IOF-SMF30LEN,        X
               TYPE=T_DEC2,JSON=asid

         SMF_FIELD SMF30CPT-SMF30PTY,TRIPLET=SMF30COF-SMF30LEN,        X
               TYPE=T_DEC4,JSON=cpu_step_time

         SMF_FIELD SMF30CPS-SMF30PTY,TRIPLET=SMF30COF-SMF30LEN,        X
               TYPE=T_DEC4,JSON=srb_time

         SMF_FIELD SMF30ICU-SMF30PTY,TRIPLET=SMF30COF-SMF30LEN,        X
               TYPE=T_DEC4,JSON=init_tcb_time

         SMF_FIELD SMF30ISB-SMF30PTY,TRIPLET=SMF30COF-SMF30LEN,        X
               TYPE=T_DEC4,JSON=init_srb_time

         SMF_FIELD SMF30IST-SMF30PTY,TRIPLET=SMF30COF-SMF30LEN,        X
               TYPE=T_DEC4,JSON=interval_start

         SMF_FIELD SMF30IDT-SMF30PTY,TRIPLET=SMF30COF-SMF30LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF30CSC-SMF30PTY,TRIPLET=SMF30COF-SMF30LEN,        X
               TYPE=T_DEC4,JSON=crypto_count

         SMF_FIELD SMF30SCC-SMF30SCC,TRIPLET=SMF30TOF-SMF30LEN,        X
               TYPE=T_HEX2,JSON=step_comp_code

         SMF_FIELD SMF30ARC-SMF30SCC,TRIPLET=SMF30TOF-SMF30LEN,        X
               TYPE=T_DEC4,JSON=abend_reason
