* ====================================================================
* SMF TYPE 42 SUBTYPE 15 — VSAM RLS CF storage class response time
* From catalog/smf42 (IBM Docs scrape). Nested DS sections omitted
* (offsets live inside job header — not fixed TRIPLET-safe).
* ====================================================================
TABLE42_15 SMF_START

* --- Header/Self-defining section ---
         SMF_FIELD SMF42RTY-SMF42RCL,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF42TME-SMF42RCL,TYPE=T_TME,JSON=time

         SMF_FIELD SMF42DTE-SMF42RCL,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF42SID-SMF42RCL,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF42SSI-SMF42RCL,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF42STY-SMF42RCL,TYPE=T_DEC2,JSON=subtype

* --- Sysplex-wide storage class summary data section for below the bar via SMF42SCO ---
         SMF_FIELD SMF42FAA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=faa

         SMF_FIELD SMF42FAB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC2,JSON=fab

         SMF_FIELD SMF42F01-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC2,JSON=f01

         SMF_FIELD SMF42FAE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fae

         SMF_FIELD SMF42FAF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=faf

         SMF_FIELD SMF42FAG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fag

         SMF_FIELD SMF42F02-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC2,JSON=f02

         SMF_FIELD SMF42F12-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC2,JSON=f12

         SMF_FIELD SMF42FY3-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC1,JSON=fy3

         SMF_FIELD SMF42FSA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fsa

         SMF_FIELD SMF42FSB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fsb

         SMF_FIELD SMF42FCA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fca

         SMF_FIELD SMF42FCB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcb

         SMF_FIELD SMF42FCC-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcc

         SMF_FIELD SMF42FCD-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcd

         SMF_FIELD SMF42FCE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fce

         SMF_FIELD SMF42FCF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcf

         SMF_FIELD SMF42FCG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcg

         SMF_FIELD SMF42FCH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fch

         SMF_FIELD SMF42FCI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fci

         SMF_FIELD SMF42FCJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcj

         SMF_FIELD SMF42FCK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fck

         SMF_FIELD SMF42FCL-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcl

         SMF_FIELD SMF42FCM-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcm

         SMF_FIELD SMF42FCN-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcn

         SMF_FIELD SMF42FCO-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fco

         SMF_FIELD SMF42FCP-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcp

         SMF_FIELD SMF42FCR-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcr

         SMF_FIELD SMF42FCS-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcs

         SMF_FIELD SMF42FCX-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcx

         SMF_FIELD SMF42FCY-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fcy

         SMF_FIELD SMF42FCZ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=fcz

         SMF_FIELD SMF42FDA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fda

         SMF_FIELD SMF42FDB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdb

         SMF_FIELD SMF42FDC-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdc

         SMF_FIELD SMF42FDD-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdd

         SMF_FIELD SMF42FDE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fde

         SMF_FIELD SMF42FDF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdf

         SMF_FIELD SMF42FDG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdg

         SMF_FIELD SMF42FDH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdh

         SMF_FIELD SMF42FDI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdi

         SMF_FIELD SMF42FDJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdj

         SMF_FIELD SMF42FDK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdk

         SMF_FIELD SMF42FDL-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdl

         SMF_FIELD SMF42FDM-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdm

         SMF_FIELD SMF42FDN-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdn

         SMF_FIELD SMF42FDO-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdo

         SMF_FIELD SMF42FDP-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdp

         SMF_FIELD SMF42FDR-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdr

         SMF_FIELD SMF42FDS-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fds

         SMF_FIELD SMF42FDX-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdx

         SMF_FIELD SMF42FDY-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fdy

         SMF_FIELD SMF42FDZ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=fdz

         SMF_FIELD SMF42FEA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fea

         SMF_FIELD SMF42FEB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=feb

         SMF_FIELD SMF42FEC-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fec

         SMF_FIELD SMF42FED-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fed

         SMF_FIELD SMF42FEE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fee

         SMF_FIELD SMF42FEF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fef

         SMF_FIELD SMF42FEG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=feg

         SMF_FIELD SMF42FEH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=feh

         SMF_FIELD SMF42FEI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fei

         SMF_FIELD SMF42FEJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fej

         SMF_FIELD SMF42FEK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fek

         SMF_FIELD SMF42FEL-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fel

         SMF_FIELD SMF42FEM-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fem

         SMF_FIELD SMF42FEN-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fen

         SMF_FIELD SMF42FEO-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=feo

         SMF_FIELD SMF42FEP-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fep

         SMF_FIELD SMF42FER-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fer

         SMF_FIELD SMF42FES-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fes

         SMF_FIELD SMF42FEX-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fex

         SMF_FIELD SMF42FEY-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fey

         SMF_FIELD SMF42FEZ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=fez

         SMF_FIELD SMF42FFA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffa

         SMF_FIELD SMF42FFB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffb

         SMF_FIELD SMF42FFC-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffc

         SMF_FIELD SMF42FFD-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffd

         SMF_FIELD SMF42FFE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffe

         SMF_FIELD SMF42FFF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fff

         SMF_FIELD SMF42FFG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffg

         SMF_FIELD SMF42FFH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffh

         SMF_FIELD SMF42FFI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffi

         SMF_FIELD SMF42FFJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffj

         SMF_FIELD SMF42FFK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffk

         SMF_FIELD SMF42FFL-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffl

         SMF_FIELD SMF42FFM-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffm

         SMF_FIELD SMF42FFN-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffn

         SMF_FIELD SMF42FFO-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffo

         SMF_FIELD SMF42FFP-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffp

         SMF_FIELD SMF42FFR-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffr

         SMF_FIELD SMF42FFS-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffs

         SMF_FIELD SMF42FFX-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffx

         SMF_FIELD SMF42FFY-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=ffy

         SMF_FIELD SMF42FFZ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=ffz

         SMF_FIELD SMF42FGA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fga

         SMF_FIELD SMF42FGB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgb

         SMF_FIELD SMF42FGC-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgc

         SMF_FIELD SMF42FGD-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgd

         SMF_FIELD SMF42FGE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fge

         SMF_FIELD SMF42FGF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgf

         SMF_FIELD SMF42FGG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgg

         SMF_FIELD SMF42FGH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgh

         SMF_FIELD SMF42FGI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgi

         SMF_FIELD SMF42FGJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgj

         SMF_FIELD SMF42FGK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgk

         SMF_FIELD SMF42FGL-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgl

         SMF_FIELD SMF42FGM-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgm

         SMF_FIELD SMF42FGN-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgn

         SMF_FIELD SMF42FGO-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgo

         SMF_FIELD SMF42FGP-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgp

         SMF_FIELD SMF42FGR-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgr

         SMF_FIELD SMF42FGS-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgs

         SMF_FIELD SMF42FGX-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgx

         SMF_FIELD SMF42FGY-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fgy

         SMF_FIELD SMF42FGZ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=fgz

         SMF_FIELD SMF42FHA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fha

         SMF_FIELD SMF42FHB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhb

         SMF_FIELD SMF42FHC-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhc

         SMF_FIELD SMF42FHD-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhd

         SMF_FIELD SMF42FHE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhe

         SMF_FIELD SMF42FHF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhf

         SMF_FIELD SMF42FHG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhg

         SMF_FIELD SMF42FHH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhh

         SMF_FIELD SMF42FHI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhi

         SMF_FIELD SMF42FHJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhj

         SMF_FIELD SMF42FHK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhk

         SMF_FIELD SMF42FHL-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhl

         SMF_FIELD SMF42FHM-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhm

         SMF_FIELD SMF42FHN-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhn

         SMF_FIELD SMF42FHO-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fho

         SMF_FIELD SMF42FHP-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhp

         SMF_FIELD SMF42FHR-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhr

         SMF_FIELD SMF42FHS-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhs

         SMF_FIELD SMF42FHX-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhx

         SMF_FIELD SMF42FHY-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fhy

         SMF_FIELD SMF42FHZ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=fhz

         SMF_FIELD SMF42FOA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foa

         SMF_FIELD SMF42FOB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fob

         SMF_FIELD SMF42FOC-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foc

         SMF_FIELD SMF42FOD-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fod

         SMF_FIELD SMF42FOE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foe

         SMF_FIELD SMF42FOF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fof

         SMF_FIELD SMF42FUA-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fua

         SMF_FIELD SMF42FUB-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fub

         SMF_FIELD SMF42FOH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foh

         SMF_FIELD SMF42FOI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foi

         SMF_FIELD SMF42FOJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foj

         SMF_FIELD SMF42FOK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fok

         SMF_FIELD SMF42FOL-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fol

         SMF_FIELD SMF42FOM-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fom

         SMF_FIELD SMF42FON-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fon

         SMF_FIELD SMF42FOO-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foo

         SMF_FIELD SMF42FOP-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fop

         SMF_FIELD SMF42FOQ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=foq

         SMF_FIELD SMF42FOR-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=for

         SMF_FIELD SMF42FOS-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fos

         SMF_FIELD SMF42FOT-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fot

         SMF_FIELD SMF42FOU-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fou

         SMF_FIELD SMF42FOV-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fov

         SMF_FIELD SMF42FOW-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fow

         SMF_FIELD SMF42FUD-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fud

         SMF_FIELD SMF42FUE-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fue

         SMF_FIELD SMF42FUF-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fuf

         SMF_FIELD SMF42FUG-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fug

         SMF_FIELD SMF42FPH-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fph

         SMF_FIELD SMF42FPI-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fpi

         SMF_FIELD SMF42FPJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fpj

         SMF_FIELD SMF42FPK-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fpk

         SMF_FIELD SMF42FPS-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fps

         SMF_FIELD SMF42FPT-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fpt

         SMF_FIELD SMF42FPU-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fpu

         SMF_FIELD SMF42FPV-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_DEC4,JSON=fpv

         SMF_FIELD SMF42FPW-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=fpw

         SMF_FIELD SMF42FAJ-SMF42FAA,TRIPLET=SMF42SCO-SMF42RCL,        X
               TYPE=T_CHR8,JSON=faj

         SMF_END
