* ====================================================================
* SMF TYPE 74 SUBTYPE 8 — Enterprise disk system statistics
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* Section fields capped: 12/section, 48 total
* ====================================================================
TABLE74_8 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE8_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE8_CONTROL_DATA_SECTION via SMF748CO ---
         SMF_FIELD R748CLVL-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=clvl

         SMF_FIELD R748CVSN-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=cvsn

         SMF_FIELD R748CRTN-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=crtn

         SMF_FIELD R748CSC-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=csc

         SMF_FIELD R748CIOC-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=cioc

         SMF_FIELD R748CFDV-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=cfdv

         SMF_FIELD R748CDEV-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_HEX2,JSON=cdev

         SMF_FIELD R748CINT-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cint

         SMF_FIELD R748CFTM-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_TME,JSON=cftm

         SMF_FIELD R748CFCI-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cfci

         SMF_FIELD R748CFSC-R748CLVL,TRIPLET=SMF748CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=cfsc

* --- section SMF74_SUBTYPE8_LINK_STATISTICS_SECTION via SMF748SO ---
         SMF_FIELD R748LAID-R748LAID,TRIPLET=SMF748SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=laid

         SMF_FIELD R748LTYP-R748LAID,TRIPLET=SMF748SO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=ltyp

         SMF_FIELD R748LFBC-R748LAID,TRIPLET=SMF748SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=lfbc

* --- section SMF74_SUBTYPE8_EXT_POOL_STATISTICS_SECTION via SMF748XO ---
         SMF_FIELD R748XPID-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=xpid

         SMF_FIELD R748XPLT-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=xplt

         SMF_FIELD R748XRCP-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xrcp

         SMF_FIELD R748XRNS-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xrns

         SMF_FIELD R748XRNA-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xrna

         SMF_FIELD R748XRSC-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xrsc

         SMF_FIELD R748XVCP-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xvcp

         SMF_FIELD R748XVNS-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xvns

         SMF_FIELD R748XVSC-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xvsc

         SMF_FIELD R748XSDY-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xsdy

         SMF_FIELD R748XTDY-R748XPID,TRIPLET=SMF748XO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=xtdy

* --- section SMF74_SUBTYPE8_RANK_STATISTICS_SECTION via SMF748RO ---
         SMF_FIELD R748RRID-R748RRID,TRIPLET=SMF748RO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rrid

         SMF_FIELD R748RPNM-R748RRID,TRIPLET=SMF748RO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rpnm

         SMF_FIELD R748RCNT-R748RRID,TRIPLET=SMF748RO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rcnt

         SMF_FIELD R748RAIX-R748RRID,TRIPLET=SMF748RO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=raix

         SMF_FIELD R748RAI-R748RRID,TRIPLET=SMF748RO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rai

* --- section SMF74_SUBTYPE8_RANK_ARRAY_DATA_SECTION via SMF748AO ---
         SMF_FIELD R748AAID-R748AAID,TRIPLET=SMF748AO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=aaid

         SMF_FIELD R748ARID-R748AAID,TRIPLET=SMF748AO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=arid

         SMF_FIELD R748ATYP-R748AAID,TRIPLET=SMF748AO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=atyp

         SMF_FIELD R748AASP-R748AAID,TRIPLET=SMF748AO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=aasp

         SMF_FIELD R748AAWD-R748AAID,TRIPLET=SMF748AO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=aawd

         SMF_FIELD R748AACP-R748AAID,TRIPLET=SMF748AO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=aacp

         SMF_END
