* ====================================================================
* SMF TYPE 74 SUBTYPE 5 — Cache subsystem device activity
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* Section fields capped: 12/section, 48 total
* ====================================================================
TABLE74_5 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE5_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE5_CACHE_CONTROL_SECTION via SMF745CO ---
         SMF_FIELD R745CLVL-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=clvl

         SMF_FIELD R745CMDL-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=cmdl

         SMF_FIELD R745CCNT-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=ccnt

         SMF_FIELD R745CSC-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=csc

         SMF_FIELD R745CRTN-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=crtn

         SMF_FIELD R745CIOC-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=cioc

         SMF_FIELD R745CINT-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cint

         SMF_FIELD NEDPMANU-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_CHR2,JSON=nedpmanu

         SMF_FIELD NEDTAG-R745CLVL,TRIPLET=SMF745CO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=nedtag

* --- section SMF74_SUBTYPE5_CACHE_DEVICE_DATA_SECTION via SMF745DO ---
         SMF_FIELD R745DEVN-R745DVOL,TRIPLET=SMF745DO-SMF74LEN,        X
               TYPE=T_HEX2,JSON=devn

         SMF_FIELD R745DVID-R745DVOL,TRIPLET=SMF745DO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=dvid

         SMF_FIELD R745DSID-R745DVOL,TRIPLET=SMF745DO-SMF74LEN,        X
               TYPE=T_HEX2,JSON=dsid

* --- section SMF74_SUBTYPE5_CACHE_STATUS_DATA_SECTION via SMF745SO ---
         SMF_FIELD R745SDEV-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_HEX2,JSON=sdev

         SMF_FIELD R745SLN-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=sln

         SMF_FIELD R745SNAD-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=snad

         SMF_FIELD R745SNSS-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=snss

         SMF_FIELD R745SCLN-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=scln

         SMF_FIELD R745SCSF-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=scsf

         SMF_FIELD R745SCNF-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=scnf

         SMF_FIELD R745SAVL-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=savl

         SMF_FIELD R745SPIN-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=spin

         SMF_FIELD R745SOFF-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=soff

         SMF_FIELD R745SCNV-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=scnv

         SMF_FIELD R745SPND-R745SVOL,TRIPLET=SMF745SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=spnd

* --- section SMF74_SUBTYPE5_RAID_RANK_DATA_SECTION via SMF7451O ---
         SMF_FIELD R7451DVN-R7451DVN,TRIPLET=SMF7451O-SMF74LEN,        X
               TYPE=T_HEX2,JSON=dvn

         SMF_FIELD R7451SCS-R7451DVN,TRIPLET=SMF7451O-SMF74LEN,        X
               TYPE=T_DEC1,JSON=scs

         SMF_FIELD R7451AID-R7451DVN,TRIPLET=SMF7451O-SMF74LEN,        X
               TYPE=T_DEC1,JSON=aid

         SMF_FIELD R7452XID-R7451DVN,TRIPLET=SMF7451O-SMF74LEN,        X
               TYPE=T_DEC2,JSON=xid

         SMF_FIELD R7451HSS-R7451DVN,TRIPLET=SMF7451O-SMF74LEN,        X
               TYPE=T_DEC2,JSON=hss

         SMF_END
