* ====================================================================
* SMF TYPE 70 SUBTYPE 1 — CPU, PR/SM, and ICF activity
* ====================================================================
TABLE70_1 SMF_START

         SMF_FIELD SMF70RTY-SMF70LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF70SID-SMF70LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF70TME-SMF70LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF70DTE-SMF70LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF70SSI-SMF70LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF70STY-SMF70LEN,TYPE=T_DEC2,JSON=subtype

* --- product ---
         SMF_FIELD SMF70PRD-SMF70MFV,TRIPLET=SMF70PRS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF70DAT-SMF70MFV,TRIPLET=SMF70PRS-SMF70LEN,        X
               TYPE=T_DTE,JSON=dat

         SMF_FIELD SMF70SAM-SMF70MFV,TRIPLET=SMF70PRS-SMF70LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF70MVS-SMF70MFV,TRIPLET=SMF70PRS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF70SRL-SMF70MFV,TRIPLET=SMF70PRS-SMF70LEN,        X
               TYPE=T_DEC1,JSON=srl

         SMF_FIELD SMF70XNM-SMF70MFV,TRIPLET=SMF70PRS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF70SNM-SMF70MFV,TRIPLET=SMF70PRS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- CPU control ---
         SMF_FIELD SMF70MOD-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_HEX2,JSON=cpu_family

         SMF_FIELD SMF70VER-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_DEC1,JSON=ver

         SMF_FIELD SMF70BNP-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_DEC1,JSON=phys_cpu_count

         SMF_FIELD SMF70IFA-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_DEC2,JSON=zaap_online

         SMF_FIELD SMF70SUP-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_DEC2,JSON=ziip_online

         SMF_FIELD SMF70WLA-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_DEC4,JSON=wla

         SMF_FIELD SMF70LAC-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_DEC4,JSON=lac

         SMF_FIELD SMF70POM-SMF70MOD,TRIPLET=SMF70CCS-SMF70LEN,        X
               TYPE=T_CHR4,JSON=pom

* --- CPU data ---
         SMF_FIELD SMF70CID-SMF70WAT,TRIPLET=SMF70CPS-SMF70LEN,        X
               TYPE=T_DEC2,JSON=cpu_id

         SMF_FIELD SMF70TYP-SMF70WAT,TRIPLET=SMF70CPS-SMF70LEN,        X
               TYPE=T_DEC1,JSON=cpu_type

         SMF_FIELD SMF70SLH-SMF70WAT,TRIPLET=SMF70CPS-SMF70LEN,        X
               TYPE=T_DEC4,JSON=slh

         SMF_FIELD SMF70TPI-SMF70WAT,TRIPLET=SMF70CPS-SMF70LEN,        X
               TYPE=T_DEC4,JSON=tpi

* --- PR/SM partition ---
         SMF_FIELD SMF70LPM-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=lpar_name

         SMF_FIELD SMF70LPN-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_DEC1,JSON=lpar_number

         SMF_FIELD SMF70BDN-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_DEC2,JSON=bdn

         SMF_FIELD SMF70MSU-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_DEC4,JSON=defined_msu

         SMF_FIELD SMF70CSF-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_DEC4,JSON=csf

         SMF_FIELD SMF70SPN-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=spn

         SMF_FIELD SMF70STN-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=stn

         SMF_FIELD SMF70GNM-SMF70LPM,TRIPLET=SMF70BCS-SMF70LEN,        X
               TYPE=T_CHR8,JSON=gnm

         SMF_END
