* ====================================================================
* SMF TYPE 72 SUBTYPE 5 — Serialization delay
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* Section fields capped: 12/section, 48 total
* ====================================================================
TABLE72_5 SMF_START

         SMF_FIELD SMF72RTY-SMF72LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF72SID-SMF72LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF72TME-SMF72LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF72DTE-SMF72LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF72SSI-SMF72LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF72STY-SMF72LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF72_SUBTYPE5_PRODUCT_SECTION via SMF72PRS ---
         SMF_FIELD SMF72PRD-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF72DAT-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF72SAM-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF72MVS-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF72SRL-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF72RAO-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF72RAL-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF72RAN-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF72OIL-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF72SYN-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF72XNM-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF72SNM-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF72_SUBTYPE5_SERIALIZATION_CONTROL_SECTION via SMF72SES ---
         SMF_FIELD R725SGMO-R725SGMO,TRIPLET=SMF72SES-SMF72LEN,        X
               TYPE=T_DEC1,JSON=sgmo

* --- section SMF72_SUBTYPE5_CMS_LOCK_DATA via SMF72CMS ---
         SMF_FIELD R725CMJN-R725CMJN,TRIPLET=SMF72CMS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=cmjn

         SMF_FIELD R725CMSP-R725CMJN,TRIPLET=SMF72CMS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=cmsp

         SMF_FIELD R725CMAS-R725CMJN,TRIPLET=SMF72CMS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=cmas

         SMF_FIELD R725CMSN-R725CMJN,TRIPLET=SMF72CMS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=cmsn

         SMF_FIELD R725CMTY-R725CMJN,TRIPLET=SMF72CMS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=cmty

         SMF_FIELD R725CM_ENTRY_INDEX-R725CMJN,TRIPLET=SMF72CMS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=cmentryindex

         SMF_FIELD R725CM_SERVICE_CLASS_LIST_INDEX-R725CMJN,TRIPLET=SMF72CMS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=cmserviceclassli

* --- section SMF72_SUBTYPE5_CMS_LATCH_LOCK_DATA via SMF72LAS ---
         SMF_FIELD R725CMJN-R725CMJN,TRIPLET=SMF72LAS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=cmjn2

         SMF_FIELD R725CMSP-R725CMJN,TRIPLET=SMF72LAS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=cmsp2

         SMF_FIELD R725CMAS-R725CMJN,TRIPLET=SMF72LAS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=cmas2

         SMF_FIELD R725CMSN-R725CMJN,TRIPLET=SMF72LAS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=cmsn2

         SMF_FIELD R725CMTY-R725CMJN,TRIPLET=SMF72LAS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=cmty2

         SMF_FIELD R725CM_ENTRY_INDEX-R725CMJN,TRIPLET=SMF72LAS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=cmentryindex2

         SMF_FIELD R725CM_SERVICE_CLASS_LIST_INDEX-R725CMJN,TRIPLET=SMF72LAS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=cmserviceclassl2

* --- section SMF72_SUBTYPE5_LOCAL_LOCK_DATA via SMF72LOS ---
         SMF_FIELD R725LOJN-R725LOJN,TRIPLET=SMF72LOS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=lojn

         SMF_FIELD R725LOSP-R725LOJN,TRIPLET=SMF72LOS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=losp

         SMF_FIELD R725LOAS-R725LOJN,TRIPLET=SMF72LOS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=loas

         SMF_FIELD R725LOSN-R725LOJN,TRIPLET=SMF72LOS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=losn

         SMF_FIELD R725LO_ENTRY_INDEX-R725LOJN,TRIPLET=SMF72LOS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=loentryindex

         SMF_FIELD R725LO_SERVICE_CLASS_LIST_INDEX-R725LOJN,TRIPLET=SMF72LOS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=loserviceclassli

* --- section SMF72_SUBTYPE5_CML_LOCK_OWNER_DATA via SMF72COS ---
         SMF_FIELD R725COJN-R725COJN,TRIPLET=SMF72COS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=cojn

         SMF_FIELD R725COSP-R725COJN,TRIPLET=SMF72COS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=cosp

         SMF_FIELD R725COAS-R725COJN,TRIPLET=SMF72COS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=coas

         SMF_FIELD R725COSN-R725COJN,TRIPLET=SMF72COS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=cosn

         SMF_FIELD R725CO_ENTRY_INDEX-R725COJN,TRIPLET=SMF72COS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=coentryindex

         SMF_FIELD R725CO_SERVICE_CLASS_LIST_INDEX-R725COJN,TRIPLET=SMF72COS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=coserviceclassli

* --- section SMF72_SUBTYPE5_CML_LOCK_REQUESTOR_DATA via SMF72CRS ---
         SMF_FIELD R725CRJN-R725CRJN,TRIPLET=SMF72CRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=crjn

         SMF_FIELD R725CRSP-R725CRJN,TRIPLET=SMF72CRS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=crsp

         SMF_FIELD R725CRAS-R725CRJN,TRIPLET=SMF72CRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=cras

         SMF_FIELD R725CRSN-R725CRJN,TRIPLET=SMF72CRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=crsn

         SMF_FIELD R725CR_ENTRY_INDEX-R725CRJN,TRIPLET=SMF72CRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=crentryindex

         SMF_FIELD R725CR_SERVICE_CLASS_LIST_INDEX-R725CRJN,TRIPLET=SMF72CRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=crserviceclassli

* --- section SMF72_SUBTYPE5_GRS_LATCH_SET_CREATOR_DATA via SMF72LCS ---
         SMF_FIELD R725LAJN-R725LAJN,TRIPLET=SMF72LCS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=lajn

         SMF_FIELD R725LASP-R725LAJN,TRIPLET=SMF72LCS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=lasp

         SMF_FIELD R725LAAS-R725LAJN,TRIPLET=SMF72LCS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=laas

         SMF_END
