* ====================================================================
* SMF TYPE 74 SUBTYPE 4 — Coupling facility activity
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* Section fields capped: 12/section, 48 total
* ====================================================================
TABLE74_4 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE4_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE4_LOCAL_CF_DATA_SECTION via SMF744FO ---
         SMF_FIELD R744FNAM-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=fnam

         SMF_FIELD R744FSYS-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=fsys

         SMF_FIELD R744FAMV-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=famv

         SMF_FIELD R744FPAM-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fpam

         SMF_FIELD R744FSCG-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fscg

         SMF_FIELD R744FSCU-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fscu

         SMF_FIELD R744FSCL-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fscl

         SMF_FIELD R744FMPC-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_CHR2,JSON=fmpc

         SMF_FIELD R744FLPN-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=flpn

         SMF_FIELD R744FLVL-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=flvl

         SMF_FIELD R744FPSN-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fpsn

         SMF_FIELD R744FPDN-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fpdn

* --- section SMF74_SUBTYPE4_STORAGE_DATA_SECTION via SMF744GO ---
         SMF_FIELD R744GCSD-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gcsd

         SMF_FIELD R744GCSF-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gcsf

         SMF_FIELD R744GTSD-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gtsd

         SMF_FIELD R744GTSF-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gtsf

         SMF_FIELD R744GDSA-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gdsa

         SMF_FIELD R744GDSF-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gdsf

         SMF_FIELD R744GDSR-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gdsr

         SMF_FIELD R744GISC-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=gisc

* --- section SMF74_SUBTYPE4_CONNECTIVITY_DATA_SECTION via SMF744XO ---
         SMF_FIELD R744XSYS-R744XSYS,TRIPLET=SMF744XO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=xsys

* --- section SMF74_SUBTYPE4_STRUCTURE_DATA_SECTION via SMF744QO ---
         SMF_FIELD R744QSIZ-R744QSTR,TRIPLET=SMF744QO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=qsiz

* --- section SMF74_SUBTYPE4_REQUEST_DATA_SECTION via SMF744SO ---
         SMF_FIELD R744SLEC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=slec

         SMF_FIELD R744SLEL-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slel

         SMF_FIELD R744SLEM-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slem

         SMF_FIELD R744SLTL-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sltl

         SMF_FIELD R744SLTM-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sltm

         SMF_FIELD R744SHMN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=shmn

         SMF_FIELD R744SHMX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=shmx

         SMF_FIELD R744SLMN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slmn

         SMF_FIELD R744SLMX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slmx

         SMF_FIELD R744SDMN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sdmn

         SMF_FIELD R744SDMX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sdmx

         SMF_FIELD R744SSIZ-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ssiz

* --- section SMF74_SUBTYPE4_PROCESSOR_UTILIZATION_DATA_SECTION via SMF744PO ---
         SMF_FIELD R744PNUM-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pnum

         SMF_FIELD R744PBSY-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pbsy

         SMF_END
