* ====================================================================
* SMF TYPE 74 SUBTYPE 6 — HFS statistics
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* Section fields capped: 12/section, 48 total
* ====================================================================
TABLE74_6 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE6_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE6_GLOBAL_DATA_SECTION via SMF746DO ---
         SMF_FIELD R746GMXV-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gmxv

         SMF_FIELD R746GUSV-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gusv

         SMF_FIELD R746GMNF-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gmnf

         SMF_FIELD R746GUSF-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gusf

         SMF_FIELD R746GLRC-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=glrc

         SMF_FIELD R746GLRS-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=glrs

         SMF_FIELD R746GSRC-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gsrc

         SMF_FIELD R746GSRS-R746GMXV,TRIPLET=SMF746DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gsrs

* --- section SMF74_SUBTYPE6_GLOBAL_BUFFER_SECTION via SMF746BO ---
         SMF_FIELD R746GSB-R746GSB,TRIPLET=SMF746BO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=gsb

         SMF_FIELD R746GNDS-R746GSB,TRIPLET=SMF746BO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=gnds

         SMF_FIELD R746GSBP-R746GSB,TRIPLET=SMF746BO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gsbp

         SMF_FIELD R746GSBF-R746GSB,TRIPLET=SMF746BO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gsbf

* --- section SMF74_SUBTYPE6_FILE_SYSTEM_SECTION via SMF746FO ---
         SMF_FIELD R746FSNL-R746FSNM,TRIPLET=SMF746FO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=fsnl

         SMF_FIELD R746FSF-R746FSNM,TRIPLET=SMF746FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fsf

         SMF_FIELD R746FPF-R746FSNM,TRIPLET=SMF746FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fpf

         SMF_FIELD R746FPD-R746FSNM,TRIPLET=SMF746FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fpd

         SMF_FIELD R746FPC-R746FSNM,TRIPLET=SMF746FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fpc

         SMF_FIELD R746FSRC-R746FSNM,TRIPLET=SMF746FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fsrc

         SMF_FIELD R746FSRS-R746FSNM,TRIPLET=SMF746FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fsrs

         SMF_END
