* ====================================================================
* SMF TYPE 74 SUBTYPE 1 — Device activity
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* All supported T_* section fields (no per-section caps)
* ====================================================================
TABLE74_1 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE1_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE1_DEVICE_CONTROL_DATA via SMF74DCS ---
         SMF_FIELD SMF74NXT-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=nxt

         SMF_FIELD SMF74TOT-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=tot

         SMF_FIELD SMF74GEN-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=gen

         SMF_FIELD SMF74SUB-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_HEX2,JSON=sub

         SMF_FIELD SMF74S15-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=s15

         SMF_FIELD SMF74SRC-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=src

         SMF_FIELD SMF74SRS-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=srs

         SMF_FIELD SMF74TSR-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=tsr

         SMF_FIELD SMF74LSN-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=lsn

         SMF_FIELD SMF74TSF-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_CHR2,JSON=tsf

         SMF_FIELD SMF74TDT-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=tdt

         SMF_FIELD SMF74TTM-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=ttm

         SMF_FIELD SMF74MCT-SMF74NXT,TRIPLET=SMF74DCS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=mct

* --- section SMF74_SUBTYPE1_DEVICE_DATA via SMF74DDS ---
         SMF_FIELD SMF74NUM-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_HEX2,JSON=device_num

         SMF_FIELD SMF74LCU-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_HEX2,JSON=lcu_num

         SMF_FIELD SMF74SSC-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ssch_count

         SMF_FIELD SMF74CNN-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=connect_time

         SMF_FIELD SMF74PEN-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pending_time

         SMF_FIELD SMF74NUX-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=nux

         SMF_FIELD SMF74MEC-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=mec

         SMF_FIELD SMF74ATV-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=atv

         SMF_FIELD SMF74DIS-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=dis

         SMF_FIELD SMF74QUE-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=que

         SMF_FIELD SMF74UTL-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=utl

         SMF_FIELD SMF74RSV-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rsv

         SMF_FIELD SMF74ALC-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=alc

         SMF_FIELD SMF74MTP-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=mtp

         SMF_FIELD SMF74NRD-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=nrd

         SMF_FIELD SMF74COF-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=cof

         SMF_FIELD SMF74DVB-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=dvb

         SMF_FIELD SMF74SGN-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sgn

         SMF_FIELD SMF74NDA-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=nda

         SMF_FIELD SMF74DEV-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=dev

         SMF_FIELD SMF74CU-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=cu

         SMF_FIELD SMF74MTC-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=mtc

         SMF_FIELD SMF74NDN-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_CHR4,JSON=ndn

         SMF_FIELD SMF74HPC-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=hpc

         SMF_FIELD SMF74NSS-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=nss

         SMF_FIELD SMF74PSM-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=psm

         SMF_FIELD SMF74PCT-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pct

         SMF_FIELD SMF74CMR-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cmr

         SMF_FIELD SMF74CAP-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cap

         SMF_FIELD SMF74IDT-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=idt

         SMF_FIELD SMF74CUQ-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cuq

         SMF_FIELD SMF74SCS-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=scs

         SMF_FIELD SMF74NM2-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_HEX2,JSON=nm2

         SMF_FIELD SMF74ATD-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=atd

         SMF_FIELD SMF74AGC-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=agc

         SMF_FIELD SMF74AGS-SMF74NUM,TRIPLET=SMF74DDS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ags

         SMF_END
