* ====================================================================
* SMF TYPE 74 SUBTYPE 4 — Coupling facility activity
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* All supported T_* section fields (no per-section caps)
* ====================================================================
TABLE74_4 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE4_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE4_LOCAL_CF_DATA_SECTION via SMF744FO ---
         SMF_FIELD R744FNAM-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=fnam

         SMF_FIELD R744FSYS-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=fsys

         SMF_FIELD R744FAMV-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=famv

         SMF_FIELD R744FPAM-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fpam

         SMF_FIELD R744FSCG-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fscg

         SMF_FIELD R744FSCU-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fscu

         SMF_FIELD R744FSCL-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fscl

         SMF_FIELD R744FMPC-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_CHR2,JSON=fmpc

         SMF_FIELD R744FLPN-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=flpn

         SMF_FIELD R744FLVL-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=flvl

         SMF_FIELD R744FPSN-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fpsn

         SMF_FIELD R744FPDN-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fpdn

         SMF_FIELD R744FCPI-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fcpi

         SMF_FIELD R744FCPN-R744FNAM,TRIPLET=SMF744FO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fcpn

* --- section SMF74_SUBTYPE4_STORAGE_DATA_SECTION via SMF744GO ---
         SMF_FIELD R744GCSD-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gcsd

         SMF_FIELD R744GCSF-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gcsf

         SMF_FIELD R744GTSD-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gtsd

         SMF_FIELD R744GTSF-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gtsf

         SMF_FIELD R744GDSA-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gdsa

         SMF_FIELD R744GDSF-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gdsf

         SMF_FIELD R744GDSR-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=gdsr

         SMF_FIELD R744GISC-R744GCSD,TRIPLET=SMF744GO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=gisc

* --- section SMF74_SUBTYPE4_CONNECTIVITY_DATA_SECTION via SMF744XO ---
         SMF_FIELD R744XSYS-R744XSYS,TRIPLET=SMF744XO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=xsys

* --- section SMF74_SUBTYPE4_STRUCTURE_DATA_SECTION via SMF744QO ---
         SMF_FIELD R744QSIZ-R744QSTR,TRIPLET=SMF744QO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=qsiz

* --- section SMF74_SUBTYPE4_REQUEST_DATA_SECTION via SMF744SO ---
         SMF_FIELD R744SLEC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=slec

         SMF_FIELD R744SLEL-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slel

         SMF_FIELD R744SLEM-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slem

         SMF_FIELD R744SLTL-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sltl

         SMF_FIELD R744SLTM-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sltm

         SMF_FIELD R744SHMN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=shmn

         SMF_FIELD R744SHMX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=shmx

         SMF_FIELD R744SLMN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slmn

         SMF_FIELD R744SLMX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=slmx

         SMF_FIELD R744SDMN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sdmn

         SMF_FIELD R744SDMX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sdmx

         SMF_FIELD R744SSIZ-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ssiz

         SMF_FIELD R744SMAS-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smas

         SMF_FIELD R744SMIS-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smis

         SMF_FIELD R744SDEC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sdec

         SMF_FIELD R744SDEL-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sdel

         SMF_FIELD R744SNLH-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=snlh

         SMF_FIELD R744SMAE-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smae

         SMF_FIELD R744SCUE-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=scue

         SMF_FIELD R744CDSI-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=cdsi

         SMF_FIELD R744CDNE-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=cdne

         SMF_FIELD R744SISC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=sisc

         SMF_FIELD R744SNSC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=snsc

         SMF_FIELD R744SSAC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ssac

         SMF_FIELD R744SOSA-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sosa

         SMF_FIELD R744SIAD-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=siad

         SMF_FIELD R744SADN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=sadn

         SMF_FIELD R744SIXC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sixc

         SMF_FIELD R744SXSC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sxsc

         SMF_FIELD R744SADO-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sado

         SMF_FIELD R744SADR-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sadr

         SMF_FIELD R744SQCH-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=sqch

         SMF_FIELD R744SWDR-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=swdr

         SMF_FIELD R744SWAC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=swac

         SMF_FIELD R744SRDR-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=srdr

         SMF_FIELD R744SRAC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=srac

         SMF_FIELD R744SWEC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=swec

         SMF_FIELD R744SREC-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=srec

         SMF_FIELD R744SMMN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smmn

         SMF_FIELD R744SMMX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smmx

         SMF_FIELD R744SMHN-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smhn

         SMF_FIELD R744SMHX-R744SNAM,TRIPLET=SMF744SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smhx

* --- section SMF74_SUBTYPE4_PROCESSOR_UTILIZATION_DATA_SECTION via SMF744PO ---
         SMF_FIELD R744PNUM-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pnum

         SMF_FIELD R744PBSY-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pbsy

         SMF_FIELD R744PWAI-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pwai

         SMF_FIELD R744PWGT-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=pwgt

         SMF_FIELD R744PBSG-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=pbsg

         SMF_FIELD R744PCCT-R744PNUM,TRIPLET=SMF744PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pcct

* --- section SMF74_SUBTYPE4_CACHE_DATA_SECTION via SMF744CO ---
         SMF_FIELD R744CDEC-R744CRHC,TRIPLET=SMF744CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdec

         SMF_FIELD R744CDAC-R744CRHC,TRIPLET=SMF744CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdac

         SMF_FIELD R744CTCC-R744CRHC,TRIPLET=SMF744CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ctcc

         SMF_FIELD R744CDTA-R744CRHC,TRIPLET=SMF744CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdta

* --- section SMF74_SUBTYPE4_REMOTE_FACILITY_DATA_SECTION via SMF744RO ---
         SMF_FIELD R744RNAM-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=rnam

         SMF_FIELD R744RRES-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rres

         SMF_FIELD R744RRCS-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rrcs

         SMF_FIELD R744RHES-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rhes

         SMF_FIELD R744RRSS-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rrss

         SMF_FIELD R744RRSA-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rrsa

         SMF_FIELD R744RSST-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rsst

         SMF_FIELD R744RDSC-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rdsc

         SMF_FIELD R744RSDT-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rsdt

         SMF_FIELD R744RSRS-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rsrs

         SMF_FIELD R744RCPI-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rcpi

         SMF_FIELD R744RCPN-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rcpn

         SMF_FIELD R744RSC-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rsc

         SMF_FIELD R744RAMC-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ramc

         SMF_FIELD R744RAMPB-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rampb

         SMF_FIELD R744RAMNS-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ramns

         SMF_FIELD NDEPARTITION-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=ndepartition

         SMF_FIELD NDEPLANT-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_CHR2,JSON=ndeplant

         SMF_FIELD NDETAG-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_CHR2,JSON=ndetag

         SMF_FIELD NDECPCID-R744RSYS,TRIPLET=SMF744RO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=ndecpcid

* --- section SMF74_SUBTYPE4_CHANNEL_PATH_DATA_SECTION via SMF744HO ---
         SMF_FIELD R744HOPM-R744HCPI,TRIPLET=SMF744HO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=hopm

         SMF_FIELD R744HLAT-R744HCPI,TRIPLET=SMF744HO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=hlat

         SMF_FIELD R744HPCP-R744HCPI,TRIPLET=SMF744HO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=hpcp

         SMF_FIELD R744HAID-R744HCPI,TRIPLET=SMF744HO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=haid

         SMF_FIELD R744HAPN-R744HCPI,TRIPLET=SMF744HO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=hapn

         SMF_FIELD R744HSAP-R744HCPI,TRIPLET=SMF744HO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=hsap

         SMF_END
