* ====================================================================
* SMF TYPE 74 SUBTYPE 2 — XCF activity
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* Section fields capped: 12/section, 48 total
* ====================================================================
TABLE74_2 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE2_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE2_SYSTEM_DATA via SMF742SO ---
         SMF_FIELD R742SNME-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=snme

         SMF_FIELD R742SPTH-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=spth

         SMF_FIELD R742SBSY-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sbsy

         SMF_FIELD R742SNOP-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=snop

         SMF_FIELD R742SMXB-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=smxb

         SMF_FIELD R742SBIG-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sbig

         SMF_FIELD R742SFIT-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sfit

         SMF_FIELD R742SSML-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ssml

         SMF_FIELD R742SOVR-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sovr

         SMF_FIELD R742STCL-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=stcl

         SMF_FIELD R742STCN-R742SNME,TRIPLET=SMF742SO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=stcn

* --- section SMF74_SUBTYPE2_PATH_DATA via SMF742PO ---
         SMF_FIELD R742PNME-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=pnme

         SMF_FIELD R742PDEV-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_CHR4,JSON=pdev

         SMF_FIELD R742PTYP-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=ptyp

         SMF_FIELD R742PONA-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=pona

         SMF_FIELD R742PODV-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_CHR4,JSON=podv

         SMF_FIELD R742PRET-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pret

         SMF_FIELD R742PRST-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=prst

         SMF_FIELD R742PMXM-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pmxm

         SMF_FIELD R742PSIG-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=psig

         SMF_FIELD R742PQLN-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pqln

         SMF_FIELD R742PIBR-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=pibr

         SMF_FIELD R742PSUS-R742PNME,TRIPLET=SMF742PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=psus

* --- section SMF74_SUBTYPE2_MEMBER_DATA via SMF742MO ---
         SMF_FIELD R742MSYS-R742MSYS,TRIPLET=SMF742MO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=msys

         SMF_FIELD R742MGRP-R742MSYS,TRIPLET=SMF742MO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mgrp

         SMF_FIELD R742MST1-R742MSYS,TRIPLET=SMF742MO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=mst1

         SMF_FIELD R742MSNT-R742MSYS,TRIPLET=SMF742MO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=msnt

         SMF_FIELD R742MRCV-R742MSYS,TRIPLET=SMF742MO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=mrcv

         SMF_FIELD R742MINT-R742MSYS,TRIPLET=SMF742MO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=mint

         SMF_FIELD R742MJOB-R742MSYS,TRIPLET=SMF742MO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mjob

         SMF_END
