* ====================================================================
* SMF TYPE 74 SUBTYPE 10 — EADM statistics
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* All supported T_* section fields (no per-section caps)
* ====================================================================
TABLE74_10 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE10_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE10_EADM_DEVICE_INFORMATION_SECTION via SMF7410DO ---
         SMF_FIELD R7410DSCT-R7410DSCT,TRIPLET=SMF7410DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=dsct

         SMF_FIELD R7410DNUM-R7410DSCT,TRIPLET=SMF7410DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=dnum

         SMF_FIELD R7410DOCC-R7410DSCT,TRIPLET=SMF7410DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=docc

         SMF_FIELD R7410DOCD-R7410DSCT,TRIPLET=SMF7410DO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=docd

* --- section SMF74_SUBTYPE10_SCM_CONFIGURATION_MEASUREMENT_SECTION via SMF7410CO ---
         SMF_FIELD R7410CRID-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=crid

         SMF_FIELD R7410CPID-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=cpid

         SMF_FIELD R7410CDUS-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdus

         SMF_FIELD R7410CRQC-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=crqc

         SMF_FIELD R7410CRQ-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=crq

         SMF_FIELD R7410CDWC-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdwc

         SMF_FIELD R7410CDW-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdw

         SMF_FIELD R7410CDRC-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdrc

         SMF_FIELD R7410CDR-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cdr

         SMF_FIELD R7410CRTC-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=crtc

         SMF_FIELD R7410CRT-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=crt

         SMF_FIELD R7410CIQC-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ciqc

         SMF_FIELD R7410CWUC-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cwuc

         SMF_FIELD R7410CWU-R7410CRID,TRIPLET=SMF7410CO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=cwu

         SMF_END
