* ====================================================================
* SMF TYPE 74 SUBTYPE 9 — PCI Express based function activity
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* All supported T_* section fields (no per-section caps)
* ====================================================================
TABLE74_9 SMF_START

         SMF_FIELD SMF74RTY-SMF74LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF74SID-SMF74LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF74TME-SMF74LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF74DTE-SMF74LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF74SSI-SMF74LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF74STY-SMF74LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF74_SUBTYPE9_PRODUCT_SECTION via SMF74PRS ---
         SMF_FIELD SMF74PRD-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF74DAT-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF74SAM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF74MVS-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF74SRL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF74RAO-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF74RAL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF74RAN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF74OIL-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF74SYN-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF74XNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF74SNM-SMF74MFV,TRIPLET=SMF74PRS-SMF74LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF74_SUBTYPE9_PCIE_FUNCTION_DATA_SECTION via SMF749PO ---
         SMF_FIELD R749ERRT-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=errt

         SMF_FIELD R749JOBN-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_CHR8,JSON=jobn

         SMF_FIELD R749ASID-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_HEX2,JSON=asid

         SMF_FIELD R749PCID-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_HEX2,JSON=pcid

         SMF_FIELD R749ALLT-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=allt

         SMF_FIELD R749SCNT-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=scnt

         SMF_FIELD R749DMAO-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=dmao

         SMF_FIELD R749DMAN-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=dman

         SMF_FIELD R749FPFO-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fpfo

         SMF_FIELD R749FPFN-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fpfn

         SMF_FIELD R749FP1O-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fp1o

         SMF_FIELD R749FP1N-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=fp1n

         SMF_FIELD R749PORT-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=port

         SMF_FIELD R749PFT-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=pft

         SMF_FIELD R749SIOO-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=sioo

         SMF_FIELD R749SION-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=sion

         SMF_FIELD R749RTDO-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rtdo

         SMF_FIELD R749RTDN-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=rtdn

         SMF_FIELD R749LKID-R749PFID,TRIPLET=SMF749PO-SMF74LEN,        X
               TYPE=T_DEC2,JSON=lkid

* --- section SMF74_SUBTYPE9_PCIE_FUNCTION_TYPE_DATA_SECTION via SMF749DO ---
         SMF_FIELD R749DFMT-R749SRBF,TRIPLET=SMF749DO-SMF74LEN,        X
               TYPE=T_DEC1,JSON=dfmt

* --- section SMF74_SUBTYPE9_HARDWARE_ACCELERATOR_DATA_SECTION via SMF749FO ---
         SMF_FIELD R749FTYP-R749FTYP,TRIPLET=SMF749FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ftyp

         SMF_FIELD R749FRQC-R749FTYP,TRIPLET=SMF749FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=frqc

         SMF_FIELD R749FRQE-R749FTYP,TRIPLET=SMF749FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=frqe

         SMF_FIELD R749FQFL-R749FTYP,TRIPLET=SMF749FO-SMF74LEN,        X
               TYPE=T_DEC4,JSON=fqfl

* --- section SMF74_SUBTYPE9_HARDWARE_ACCELERATOR_COMPRESSION_DATA_SECTION via SMF7491O ---
         SMF_FIELD R7491DCT-R7491DIB,TRIPLET=SMF7491O-SMF74LEN,        X
               TYPE=T_DEC4,JSON=dct

         SMF_FIELD R7491ICT-R7491DIB,TRIPLET=SMF7491O-SMF74LEN,        X
               TYPE=T_DEC4,JSON=ict

         SMF_FIELD R7491BPS-R7491DIB,TRIPLET=SMF7491O-SMF74LEN,        X
               TYPE=T_DEC4,JSON=bps

* --- section SMF74_SUBTYPE9_SYNC_IO_LINK_DATA_SECTION via SMF749SO ---
         SMF_FIELD R749SNDP-R749SNDT,TRIPLET=SMF749SO-SMF74LEN,        X
               TYPE=T_CHR2,JSON=sndp

         SMF_END
