* ====================================================================
* SMF TYPE 72 SUBTYPE 4 — Storage data
* Auto-generated from Gatherer OpenAPI (tools/gen_gatherer_maps.py)
* All supported T_* section fields (no per-section caps)
* ====================================================================
TABLE72_4 SMF_START

         SMF_FIELD SMF72RTY-SMF72LEN,TYPE=T_DEC1,JSON=smf_record_type

         SMF_FIELD SMF72SID-SMF72LEN,TYPE=T_CHR4,JSON=smf_system_id

         SMF_FIELD SMF72TME-SMF72LEN,TYPE=T_TME,JSON=time

         SMF_FIELD SMF72DTE-SMF72LEN,TYPE=T_DTE,JSON=date

         SMF_FIELD SMF72SSI-SMF72LEN,TYPE=T_CHR4,JSON=subsystem_id

         SMF_FIELD SMF72STY-SMF72LEN,TYPE=T_DEC2,JSON=subtype

* --- section SMF72_SUBTYPE4_PRODUCT_SECTION via SMF72PRS ---
         SMF_FIELD SMF72PRD-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=product_name

         SMF_FIELD SMF72DAT-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DTE,JSON=interval_date

         SMF_FIELD SMF72SAM-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=sample_count

         SMF_FIELD SMF72MVS-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=mvs_level

         SMF_FIELD SMF72SRL-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=rmf_release

         SMF_FIELD SMF72RAO-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=rao

         SMF_FIELD SMF72RAL-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=ral

         SMF_FIELD SMF72RAN-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=ran

         SMF_FIELD SMF72OIL-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=oil

         SMF_FIELD SMF72SYN-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_DEC2,JSON=syn

         SMF_FIELD SMF72XNM-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=sysplex_name

         SMF_FIELD SMF72SNM-SMF72MFV,TRIPLET=SMF72PRS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=system_name

* --- section SMF72_SUBTYPE4_SERVICE_CLASS_PERIOD_DATA via SMF72CPS ---
         SMF_FIELD R724PNAM-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=pnam

         SMF_FIELD R724LCNM-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_CHR8,JSON=lcnm

         SMF_FIELD R724PER#-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC1,JSON=per

         SMF_FIELD R724USER-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=user

         SMF_FIELD R724ACTV-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=actv

         SMF_FIELD R724ACTS-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=acts

         SMF_FIELD R724IDLS-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=idls

         SMF_FIELD R724PAGE-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=page

         SMF_FIELD R724SWAP-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=swap

         SMF_FIELD R724OUTR-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=outr

         SMF_FIELD R724PGIN-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=pgin

         SMF_FIELD R724DIVS-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=divs

         SMF_FIELD R724LSSA-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=lssa

         SMF_FIELD R724PSSA-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=pssa

         SMF_FIELD R724UPRO-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=upro

         SMF_FIELD R724UDEV-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=udev

         SMF_FIELD R724DPRO-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=dpro

         SMF_FIELD R724DDEV-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=ddev

         SMF_FIELD R724DSTO-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=dsto

         SMF_FIELD R724DJES-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=djes

         SMF_FIELD R724DHSM-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=dhsm

         SMF_FIELD R724DXCF-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=dxcf

         SMF_FIELD R724DENQ-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=denq

         SMF_FIELD R724DMNT-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=dmnt

         SMF_FIELD R724DMSG-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=dmsg

         SMF_FIELD R724UNKN-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=unkn

         SMF_FIELD R724VALD-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=vald

         SMF_FIELD R724LSCT-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=lsct

         SMF_FIELD R724ESCT-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=esct

         SMF_FIELD R724PSCT-R724PNAM,TRIPLET=SMF72CPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=psct

* --- section SMF72_SUBTYPE4_SWAP_REASON_DATA via SMF72SPS ---
         SMF_FIELD R724OR1-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or1

         SMF_FIELD R724OR2-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or2

         SMF_FIELD R724OR3-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or3

         SMF_FIELD R724OR4-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or4

         SMF_FIELD R724OR5-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or5

         SMF_FIELD R724OR6-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or6

         SMF_FIELD R724OR8-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or8

         SMF_FIELD R724OR9-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or9

         SMF_FIELD R724OR10-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or10

         SMF_FIELD R724OR11-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or11

         SMF_FIELD R724OR12-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or12

         SMF_FIELD R724OR13-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or13

         SMF_FIELD R724OR14-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or14

         SMF_FIELD R724OR15-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or15

         SMF_FIELD R724OR16-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or16

         SMF_FIELD R724OR17-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or17

         SMF_FIELD R724OR18-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or18

         SMF_FIELD R724OR7A-R724OR1,TRIPLET=SMF72SPS-SMF72LEN,        X
               TYPE=T_DEC4,JSON=or7a

         SMF_END
